// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Forms.Item.Submission
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        Updated_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "form_id")]
        #pragma warning disable CS1591
        Form_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "respondent_email")]
        #pragma warning disable CS1591
        Respondent_email,
        #pragma warning restore CS1591
        [EnumMember(Value = "respondent_name")]
        #pragma warning disable CS1591
        Respondent_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "answers")]
        #pragma warning disable CS1591
        Answers,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
