// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \ats\{connectionId}\applicationstatus\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplicationstatusItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item.ApplicationstatusItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplicationstatusItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ats/{connectionId}/applicationstatus/{id}{?fields*,raw*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item.ApplicationstatusItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplicationstatusItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ats/{connectionId}/applicationstatus/{id}{?fields*,raw*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve an applicationstatus
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.AtsStatus"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AtsStatus?> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item.ApplicationstatusItemRequestBuilder.ApplicationstatusItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AtsStatus> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item.ApplicationstatusItemRequestBuilder.ApplicationstatusItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.AtsStatus>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.AtsStatus.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve an applicationstatus
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item.ApplicationstatusItemRequestBuilder.ApplicationstatusItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item.ApplicationstatusItemRequestBuilder.ApplicationstatusItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item.ApplicationstatusItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item.ApplicationstatusItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Unified.OpenApiClient.Ats.Item.Applicationstatus.Item.ApplicationstatusItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve an applicationstatus
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApplicationstatusItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.GetAtsApplicationstatusFieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.GetAtsApplicationstatusFieldsParameterItem[] Fields { get; set; }
#endif
            /// <summary>Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
