// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Analytics.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Unified.OpenApiClient.Analytics
{
    /// <summary>
    /// Builds and executes requests for operations under \analytics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnalyticsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Unified.OpenApiClient.analytics.item collection</summary>
        /// <param name="position">ID of the connection</param>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Analytics.Item.WithConnectionItemRequestBuilder"/></returns>
        public global::Soenneker.Unified.OpenApiClient.Analytics.Item.WithConnectionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("connectionId", position);
                return new global::Soenneker.Unified.OpenApiClient.Analytics.Item.WithConnectionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Analytics.AnalyticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnalyticsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Analytics.AnalyticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnalyticsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/analytics", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
