// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \datastore\{connectionId}\database\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DatabaseItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DatabaseItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/datastore/{connectionId}/database/{id}{?fields*,raw*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DatabaseItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/datastore/{connectionId}/database/{id}{?fields*,raw*}", rawUrl)
        {
        }
        /// <summary>
        /// Remove a database
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve a database
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase?> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a database
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase?> PatchAsync(global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase> PatchAsync(global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a database
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase?> PutAsync(global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase> PutAsync(global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Remove a database
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieve a database
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a database
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Update a database
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.DatastoreDatabase body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder.DatabaseItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.Item.DatabaseItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve a database
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DatabaseItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.GetDatastoreDatabaseFieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.GetDatastoreDatabaseFieldsParameterItem[] Fields { get; set; }
#endif
            /// <summary>&quot;Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
        }
        /// <summary>
        /// Update a database
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DatabaseItemRequestBuilderPatchQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.PatchDatastoreDatabaseFieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.PatchDatastoreDatabaseFieldsParameterItem[] Fields { get; set; }
#endif
            /// <summary>&quot;Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
        }
        /// <summary>
        /// Update a database
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DatabaseItemRequestBuilderPutQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.UpdateDatastoreDatabaseFieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.UpdateDatastoreDatabaseFieldsParameterItem[] Fields { get; set; }
#endif
            /// <summary>&quot;Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
