// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Ticketing.Item.Ticket.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PutFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        Updated_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "customer_id")]
        #pragma warning disable CS1591
        Customer_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "subject")]
        #pragma warning disable CS1591
        Subject,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed_at")]
        #pragma warning disable CS1591
        Closed_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "priority")]
        #pragma warning disable CS1591
        Priority,
        #pragma warning restore CS1591
        [EnumMember(Value = "category_id")]
        #pragma warning disable CS1591
        Category_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "category")]
        #pragma warning disable CS1591
        Category,
        #pragma warning restore CS1591
        [EnumMember(Value = "source")]
        #pragma warning disable CS1591
        Source,
        #pragma warning restore CS1591
        [EnumMember(Value = "source_ref")]
        #pragma warning disable CS1591
        Source_ref,
        #pragma warning restore CS1591
        [EnumMember(Value = "tags")]
        #pragma warning disable CS1591
        Tags,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_id")]
        #pragma warning disable CS1591
        User_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
