// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Models;
using Soenneker.Unified.OpenApiClient.Unified.Connection.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Unified.OpenApiClient.Unified.Connection
{
    /// <summary>
    /// Builds and executes requests for operations under \unified\connection
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConnectionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Unified.OpenApiClient.unified.connection.item collection</summary>
        /// <param name="position">ID of the Connection</param>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Unified.Connection.Item.ConnectionItemRequestBuilder"/></returns>
        public global::Soenneker.Unified.OpenApiClient.Unified.Connection.Item.ConnectionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Unified.OpenApiClient.Unified.Connection.Item.ConnectionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Unified.Connection.ConnectionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConnectionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/unified/connection{?categories*,env*,external_xref*,limit*,offset*,order*,sort*,updated_gte*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Unified.Connection.ConnectionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConnectionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/unified/connection{?categories*,env*,external_xref*,limit*,offset*,order*,sort*,updated_gte*}", rawUrl)
        {
        }
        /// <summary>
        /// List all connections
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Unified.OpenApiClient.Models.Connection&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Unified.OpenApiClient.Models.Connection>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Unified.Connection.ConnectionRequestBuilder.ConnectionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Unified.OpenApiClient.Models.Connection>> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Unified.Connection.ConnectionRequestBuilder.ConnectionRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Unified.OpenApiClient.Models.Connection>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.Connection.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Used only to import existing customer credentials; use &quot;Authorize new connection&quot; instead
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.Connection"/></returns>
        /// <param name="body">A connection represents a specific authentication of an integration.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.Connection?> PostAsync(global::Soenneker.Unified.OpenApiClient.Models.Connection body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.Connection> PostAsync(global::Soenneker.Unified.OpenApiClient.Models.Connection body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.Connection>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.Connection.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all connections
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Unified.Connection.ConnectionRequestBuilder.ConnectionRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Unified.Connection.ConnectionRequestBuilder.ConnectionRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Used only to import existing customer credentials; use &quot;Authorize new connection&quot; instead
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">A connection represents a specific authentication of an integration.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.Connection body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.Connection body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Unified.Connection.ConnectionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Unified.OpenApiClient.Unified.Connection.ConnectionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Unified.OpenApiClient.Unified.Connection.ConnectionRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List all connections
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConnectionRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter the results on these categories</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("categories")]
            public global::Soenneker.Unified.OpenApiClient.Models.ListUnifiedConnectionsCategoriesParameterItem[]? Categories { get; set; }
#nullable restore
#else
            [QueryParameter("categories")]
            public global::Soenneker.Unified.OpenApiClient.Models.ListUnifiedConnectionsCategoriesParameterItem[] Categories { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("env")]
            public string? Env { get; set; }
#nullable restore
#else
            [QueryParameter("env")]
            public string Env { get; set; }
#endif
            /// <summary>Filter the results to only those integrations for your user referenced by this value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("external_xref")]
            public string? ExternalXref { get; set; }
#nullable restore
#else
            [QueryParameter("external_xref")]
            public string ExternalXref { get; set; }
#endif
            [QueryParameter("limit")]
            public double? Limit { get; set; }
            [QueryParameter("offset")]
            public double? Offset { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            /// <summary>Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("updated_gte")]
            public string? UpdatedGte { get; set; }
#nullable restore
#else
            [QueryParameter("updated_gte")]
            public string UpdatedGte { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
