// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccountingBankfeedtransaction : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount property</summary>
        public double? Amount { get; set; }
        /// <summary>The bank_category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankCategory { get; set; }
#nullable restore
#else
        public string BankCategory { get; set; }
#endif
        /// <summary>The bankfeedaccount_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankfeedaccountId { get; set; }
#nullable restore
#else
        public string BankfeedaccountId { get; set; }
#endif
        /// <summary>dimension refs -&gt; AccountingCategory (class/department/location)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CategoryIds { get; set; }
#nullable restore
#else
        public List<string> CategoryIds { get; set; }
#endif
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_pending property</summary>
        public bool? IsPending { get; set; }
        /// <summary>The merchant_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantName { get; set; }
#nullable restore
#else
        public string MerchantName { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The posted_at property</summary>
        public DateTimeOffset? PostedAt { get; set; }
        /// <summary>The raw property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransactionRawProperty? Raw { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransactionRawProperty Raw { get; set; }
#endif
        /// <summary>The reference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>The transaction_at property</summary>
        public DateTimeOffset? TransactionAt { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransactionType? Type { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransaction"/> and sets the default values.
        /// </summary>
        public AccountingBankfeedtransaction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransaction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransaction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransaction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetStringValue(); } },
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "bank_category", n => { BankCategory = n.GetStringValue(); } },
                { "bankfeedaccount_id", n => { BankfeedaccountId = n.GetStringValue(); } },
                { "category_ids", n => { CategoryIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_pending", n => { IsPending = n.GetBoolValue(); } },
                { "merchant_name", n => { MerchantName = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "posted_at", n => { PostedAt = n.GetDateTimeOffsetValue(); } },
                { "raw", n => { Raw = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransactionRawProperty>(global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransactionRawProperty.CreateFromDiscriminatorValue); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
                { "transaction_at", n => { TransactionAt = n.GetDateTimeOffsetValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransactionType>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_id", AccountId);
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteStringValue("bank_category", BankCategory);
            writer.WriteStringValue("bankfeedaccount_id", BankfeedaccountId);
            writer.WriteCollectionOfPrimitiveValues<string>("category_ids", CategoryIds);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("currency", Currency);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_pending", IsPending);
            writer.WriteStringValue("merchant_name", MerchantName);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteDateTimeOffsetValue("posted_at", PostedAt);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransactionRawProperty>("raw", Raw);
            writer.WriteStringValue("reference", Reference);
            writer.WriteDateTimeOffsetValue("transaction_at", TransactionAt);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedtransactionType>("type", Type);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
