// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AccountingTransactionStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTED")]
        #pragma warning disable CS1591
        Posted,
        #pragma warning restore CS1591
        [EnumMember(Value = "VOID")]
        #pragma warning disable CS1591
        VoidValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
