// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AccountingCategoryType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CLASS")]
        #pragma warning disable CS1591
        ClassValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPARTMENT")]
        #pragma warning disable CS1591
        Department,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCATION")]
        #pragma warning disable CS1591
        Location,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT")]
        #pragma warning disable CS1591
        Project,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK")]
        #pragma warning disable CS1591
        Task,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPENSE")]
        #pragma warning disable CS1591
        Expense,
        #pragma warning restore CS1591
        [EnumMember(Value = "INCOME")]
        #pragma warning disable CS1591
        Income,
        #pragma warning restore CS1591
    }
}
