// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    /// <summary>INCLUSIVE / EXCLUSIVE / NONE; maps Xero LineAmountTypes (a boolean cannot represent NoTax)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AccountingQuoteTaxMode
    {
        [EnumMember(Value = "INCLUSIVE")]
        #pragma warning disable CS1591
        Inclusive,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXCLUSIVE")]
        #pragma warning disable CS1591
        Exclusive,
        #pragma warning restore CS1591
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
