// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AccountingOrganizationType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "COMPANY")]
        #pragma warning disable CS1591
        Company,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSIDIARY")]
        #pragma warning disable CS1591
        Subsidiary,
        #pragma warning restore CS1591
        [EnumMember(Value = "DIVISION")]
        #pragma warning disable CS1591
        Division,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCATION")]
        #pragma warning disable CS1591
        Location,
        #pragma warning restore CS1591
    }
}
