// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccountingQuote : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accepted_at property</summary>
        public DateTimeOffset? AcceptedAt { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>tracking categories / classes (AccountingCategory dimensions)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CategoryIds { get; set; }
#nullable restore
#else
        public List<string> CategoryIds { get; set; }
#endif
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>denormalized parties, reusing the transaction contact shape</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingTransactionContact>? Contacts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingTransactionContact> Contacts { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The currency_rate property</summary>
        public double? CurrencyRate { get; set; }
        /// <summary>The customer_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerMessage { get; set; }
#nullable restore
#else
        public string CustomerMessage { get; set; }
#endif
        /// <summary>The declined_at property</summary>
        public DateTimeOffset? DeclinedAt { get; set; }
        /// <summary>The discount_amount property</summary>
        public double? DiscountAmount { get; set; }
        /// <summary>The expires_at property</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The group_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The invoice_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceId { get; set; }
#nullable restore
#else
        public string InvoiceId { get; set; }
#endif
        /// <summary>The issued_at property</summary>
        public DateTimeOffset? IssuedAt { get; set; }
        /// <summary>The lineitems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem>? Lineitems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem> Lineitems { get; set; }
#endif
        /// <summary>The memo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Memo { get; set; }
#nullable restore
#else
        public string Memo { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The payment_terms property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingQuotePaymentTerms? PaymentTerms { get; set; }
        /// <summary>The project_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The quote_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuoteNumber { get; set; }
#nullable restore
#else
        public string QuoteNumber { get; set; }
#endif
        /// <summary>The raw property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteRawProperty? Raw { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteRawProperty Raw { get; set; }
#endif
        /// <summary>The reference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>The sent_at property</summary>
        public DateTimeOffset? SentAt { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteStatus? Status { get; set; }
        /// <summary>The sub_total_amount property</summary>
        public double? SubTotalAmount { get; set; }
        /// <summary>The summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>The tax_amount property</summary>
        public double? TaxAmount { get; set; }
        /// <summary>The tax_mode property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteTaxMode? TaxMode { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The total_amount property</summary>
        public double? TotalAmount { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Models.AccountingQuote"/> and sets the default values.
        /// </summary>
        public AccountingQuote()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.AccountingQuote"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.AccountingQuote CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Unified.OpenApiClient.Models.AccountingQuote();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accepted_at", n => { AcceptedAt = n.GetDateTimeOffsetValue(); } },
                { "category_ids", n => { CategoryIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "contacts", n => { Contacts = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingTransactionContact>(global::Soenneker.Unified.OpenApiClient.Models.AccountingTransactionContact.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "currency_rate", n => { CurrencyRate = n.GetDoubleValue(); } },
                { "customer_message", n => { CustomerMessage = n.GetStringValue(); } },
                { "declined_at", n => { DeclinedAt = n.GetDateTimeOffsetValue(); } },
                { "discount_amount", n => { DiscountAmount = n.GetDoubleValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "group_id", n => { GroupId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "invoice_id", n => { InvoiceId = n.GetStringValue(); } },
                { "issued_at", n => { IssuedAt = n.GetDateTimeOffsetValue(); } },
                { "lineitems", n => { Lineitems = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem>(global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "memo", n => { Memo = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "payment_terms", n => { PaymentTerms = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingQuotePaymentTerms>(); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
                { "quote_number", n => { QuoteNumber = n.GetStringValue(); } },
                { "raw", n => { Raw = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteRawProperty>(global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteRawProperty.CreateFromDiscriminatorValue); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
                { "sent_at", n => { SentAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteStatus>(); } },
                { "sub_total_amount", n => { SubTotalAmount = n.GetDoubleValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "tax_amount", n => { TaxAmount = n.GetDoubleValue(); } },
                { "tax_mode", n => { TaxMode = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteTaxMode>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "total_amount", n => { TotalAmount = n.GetDoubleValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("accepted_at", AcceptedAt);
            writer.WriteCollectionOfPrimitiveValues<string>("category_ids", CategoryIds);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingTransactionContact>("contacts", Contacts);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("currency", Currency);
            writer.WriteDoubleValue("currency_rate", CurrencyRate);
            writer.WriteStringValue("customer_message", CustomerMessage);
            writer.WriteDateTimeOffsetValue("declined_at", DeclinedAt);
            writer.WriteDoubleValue("discount_amount", DiscountAmount);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteStringValue("group_id", GroupId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("invoice_id", InvoiceId);
            writer.WriteDateTimeOffsetValue("issued_at", IssuedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem>("lineitems", Lineitems);
            writer.WriteStringValue("memo", Memo);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingQuotePaymentTerms>("payment_terms", PaymentTerms);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteStringValue("quote_number", QuoteNumber);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteRawProperty>("raw", Raw);
            writer.WriteStringValue("reference", Reference);
            writer.WriteDateTimeOffsetValue("sent_at", SentAt);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteStatus>("status", Status);
            writer.WriteDoubleValue("sub_total_amount", SubTotalAmount);
            writer.WriteStringValue("summary", Summary);
            writer.WriteDoubleValue("tax_amount", TaxAmount);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingQuoteTaxMode>("tax_mode", TaxMode);
            writer.WriteStringValue("title", Title);
            writer.WriteDoubleValue("total_amount", TotalAmount);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
