// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    /// <summary>where EXPIRED is derived (expires_at &lt; now), the source status is preserved in raw</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AccountingQuoteStatus
    {
        [EnumMember(Value = "DRAFT")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "SENT")]
        #pragma warning disable CS1591
        Sent,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPTED")]
        #pragma warning disable CS1591
        Accepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECLINED")]
        #pragma warning disable CS1591
        Declined,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVOICED")]
        #pragma warning disable CS1591
        Invoiced,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "VOIDED")]
        #pragma warning disable CS1591
        Voided,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETED")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
    }
}
