// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccountingInvoice : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingAttachment>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingAttachment> Attachments { get; set; }
#endif
        /// <summary>The balance_amount property</summary>
        public double? BalanceAmount { get; set; }
        /// <summary>The cancelled_at property</summary>
        public DateTimeOffset? CancelledAt { get; set; }
        /// <summary>The category_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CategoryIds { get; set; }
#nullable restore
#else
        public List<string> CategoryIds { get; set; }
#endif
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The discount_amount property</summary>
        public double? DiscountAmount { get; set; }
        /// <summary>The due_at property</summary>
        public DateTimeOffset? DueAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The invoice_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceNumber { get; set; }
#nullable restore
#else
        public string InvoiceNumber { get; set; }
#endif
        /// <summary>The lineitems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem>? Lineitems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem> Lineitems { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingMetadata>? Metadata { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingMetadata> Metadata { get; set; }
#endif
        /// <summary>The notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The paid_amount property</summary>
        public double? PaidAmount { get; set; }
        /// <summary>The paid_at property</summary>
        public DateTimeOffset? PaidAt { get; set; }
        /// <summary>The payment_collection_method property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoicePaymentCollectionMethod? PaymentCollectionMethod { get; set; }
        /// <summary>ead-only reciprocal of PaymentPayment.allocations; payments applied to this invoice</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingPaymentReference>? Payments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.AccountingPaymentReference> Payments { get; set; }
#endif
        /// <summary>The paymentterm_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymenttermId { get; set; }
#nullable restore
#else
        public string PaymenttermId { get; set; }
#endif
        /// <summary>The payment_terms property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoicePaymentTerms? PaymentTerms { get; set; }
        /// <summary>The posted_at property</summary>
        public DateTimeOffset? PostedAt { get; set; }
        /// <summary>The project_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The raw property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceRawProperty? Raw { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceRawProperty Raw { get; set; }
#endif
        /// <summary>The reference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>The refund_amount property</summary>
        public double? RefundAmount { get; set; }
        /// <summary>The refunded_at property</summary>
        public DateTimeOffset? RefundedAt { get; set; }
        /// <summary>The refund_reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefundReason { get; set; }
#nullable restore
#else
        public string RefundReason { get; set; }
#endif
        /// <summary>The send property</summary>
        public bool? Send { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceStatus? Status { get; set; }
        /// <summary>The tax_amount property</summary>
        public double? TaxAmount { get; set; }
        /// <summary>The term property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceTerm? Term { get; set; }
        /// <summary>The total_amount property</summary>
        public double? TotalAmount { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceType? Type { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoice"/> and sets the default values.
        /// </summary>
        public AccountingInvoice()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoice"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoice CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoice();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingAttachment>(global::Soenneker.Unified.OpenApiClient.Models.AccountingAttachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "balance_amount", n => { BalanceAmount = n.GetDoubleValue(); } },
                { "cancelled_at", n => { CancelledAt = n.GetDateTimeOffsetValue(); } },
                { "category_ids", n => { CategoryIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "discount_amount", n => { DiscountAmount = n.GetDoubleValue(); } },
                { "due_at", n => { DueAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "invoice_number", n => { InvoiceNumber = n.GetStringValue(); } },
                { "lineitems", n => { Lineitems = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem>(global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metadata", n => { Metadata = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingMetadata>(global::Soenneker.Unified.OpenApiClient.Models.AccountingMetadata.CreateFromDiscriminatorValue)?.AsList(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "paid_amount", n => { PaidAmount = n.GetDoubleValue(); } },
                { "paid_at", n => { PaidAt = n.GetDateTimeOffsetValue(); } },
                { "payment_collection_method", n => { PaymentCollectionMethod = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoicePaymentCollectionMethod>(); } },
                { "payment_terms", n => { PaymentTerms = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoicePaymentTerms>(); } },
                { "payments", n => { Payments = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingPaymentReference>(global::Soenneker.Unified.OpenApiClient.Models.AccountingPaymentReference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "paymentterm_id", n => { PaymenttermId = n.GetStringValue(); } },
                { "posted_at", n => { PostedAt = n.GetDateTimeOffsetValue(); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
                { "raw", n => { Raw = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceRawProperty>(global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceRawProperty.CreateFromDiscriminatorValue); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
                { "refund_amount", n => { RefundAmount = n.GetDoubleValue(); } },
                { "refund_reason", n => { RefundReason = n.GetStringValue(); } },
                { "refunded_at", n => { RefundedAt = n.GetDateTimeOffsetValue(); } },
                { "send", n => { Send = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceStatus>(); } },
                { "tax_amount", n => { TaxAmount = n.GetDoubleValue(); } },
                { "term", n => { Term = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceTerm>(); } },
                { "total_amount", n => { TotalAmount = n.GetDoubleValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceType>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingAttachment>("attachments", Attachments);
            writer.WriteDoubleValue("balance_amount", BalanceAmount);
            writer.WriteDateTimeOffsetValue("cancelled_at", CancelledAt);
            writer.WriteCollectionOfPrimitiveValues<string>("category_ids", CategoryIds);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("currency", Currency);
            writer.WriteDoubleValue("discount_amount", DiscountAmount);
            writer.WriteDateTimeOffsetValue("due_at", DueAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("invoice_number", InvoiceNumber);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingLineitem>("lineitems", Lineitems);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingMetadata>("metadata", Metadata);
            writer.WriteStringValue("notes", Notes);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteDoubleValue("paid_amount", PaidAmount);
            writer.WriteDateTimeOffsetValue("paid_at", PaidAt);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoicePaymentCollectionMethod>("payment_collection_method", PaymentCollectionMethod);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.AccountingPaymentReference>("payments", Payments);
            writer.WriteStringValue("paymentterm_id", PaymenttermId);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoicePaymentTerms>("payment_terms", PaymentTerms);
            writer.WriteDateTimeOffsetValue("posted_at", PostedAt);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceRawProperty>("raw", Raw);
            writer.WriteStringValue("reference", Reference);
            writer.WriteDoubleValue("refund_amount", RefundAmount);
            writer.WriteDateTimeOffsetValue("refunded_at", RefundedAt);
            writer.WriteStringValue("refund_reason", RefundReason);
            writer.WriteBoolValue("send", Send);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceStatus>("status", Status);
            writer.WriteDoubleValue("tax_amount", TaxAmount);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceTerm>("term", Term);
            writer.WriteDoubleValue("total_amount", TotalAmount);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.AccountingInvoiceType>("type", Type);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
