// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ClubsActivityType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "RUNNING")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
        [EnumMember(Value = "CYCLING")]
        #pragma warning disable CS1591
        Cycling,
        #pragma warning restore CS1591
        [EnumMember(Value = "SWIMMING")]
        #pragma warning disable CS1591
        Swimming,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRIATHLON")]
        #pragma warning disable CS1591
        Triathlon,
        #pragma warning restore CS1591
        [EnumMember(Value = "WALKING")]
        #pragma warning disable CS1591
        Walking,
        #pragma warning restore CS1591
        [EnumMember(Value = "HIKING")]
        #pragma warning disable CS1591
        Hiking,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
