// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ClubsEventStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SCHEDULED")]
        #pragma warning disable CS1591
        Scheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELED")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "TBD")]
        #pragma warning disable CS1591
        Tbd,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINAL")]
        #pragma warning disable CS1591
        Final,
        #pragma warning restore CS1591
    }
}
