// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    /// <summary>
    /// ClubActivity (getClubActivitiesById, NO id) and the full DetailedActivity (getActivityById).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClubsActivity : IAdditionalDataHolder, IParsable
    {
        /// <summary>The number of achievements gained during this activity</summary>
        public double? AchievementCount { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of athletes that took part in this activity</summary>
        public double? AthleteCount { get; set; }
        /// <summary>The id of the athlete who performed the activity (DetailedActivity only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AthleteId { get; set; }
#nullable restore
#else
        public string AthleteId { get; set; }
#endif
        /// <summary>The full name of the athlete</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AthleteName { get; set; }
#nullable restore
#else
        public string AthleteName { get; set; }
#endif
        /// <summary>The activity&apos;s average cadence</summary>
        public double? AverageCadence { get; set; }
        /// <summary>The activity&apos;s average heart rate, in beats per minute</summary>
        public double? AverageHeartrate { get; set; }
        /// <summary>The activity&apos;s average speed, in meters per second</summary>
        public double? AverageSpeed { get; set; }
        /// <summary>The activity&apos;s average power output, in watts</summary>
        public double? AverageWatts { get; set; }
        /// <summary>The number of kilocalories consumed during this activity</summary>
        public double? Calories { get; set; }
        /// <summary>The number of comments for this activity</summary>
        public double? CommentCount { get; set; }
        /// <summary>The date that this activity was created (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The description of the activity (DetailedActivity only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The activity&apos;s distance, in meters</summary>
        public double? Distance { get; set; }
        /// <summary>The activity&apos;s elapsed time, in seconds</summary>
        public double? ElapsedTime { get; set; }
        /// <summary>The activity&apos;s highest elevation, in meters (DetailedActivity only)</summary>
        public double? ElevationHigh { get; set; }
        /// <summary>The activity&apos;s lowest elevation, in meters (DetailedActivity only)</summary>
        public double? ElevationLow { get; set; }
        /// <summary>The group this activity was listed under (reference to HrisGroup)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>Whether the activity has heart rate data</summary>
        public bool? HasHeartrate { get; set; }
        /// <summary>Unique identifier for this activity (not provided by ClubActivity)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this activity is a commute</summary>
        public bool? IsCommute { get; set; }
        /// <summary>Whether this activity was created manually</summary>
        public bool? IsManual { get; set; }
        /// <summary>Whether this activity is private</summary>
        public bool? IsPrivate { get; set; }
        /// <summary>Whether this activity was recorded on a training machine</summary>
        public bool? IsTrainer { get; set; }
        /// <summary>The total work done, in kilojoules</summary>
        public double? Kilojoules { get; set; }
        /// <summary>The number of kudos given for this activity</summary>
        public double? KudosCount { get; set; }
        /// <summary>The detailed polyline of the activity&apos;s map</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MapPolyline { get; set; }
#nullable restore
#else
        public string MapPolyline { get; set; }
#endif
        /// <summary>The summary polyline of the activity&apos;s map</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MapSummaryPolyline { get; set; }
#nullable restore
#else
        public string MapSummaryPolyline { get; set; }
#endif
        /// <summary>The activity&apos;s max heart rate, in beats per minute</summary>
        public double? MaxHeartrate { get; set; }
        /// <summary>The activity&apos;s max speed, in meters per second</summary>
        public double? MaxSpeed { get; set; }
        /// <summary>The activity&apos;s max power output, in watts</summary>
        public double? MaxWatts { get; set; }
        /// <summary>The activity&apos;s moving time, in seconds</summary>
        public double? MovingTime { get; set; }
        /// <summary>The name of the activity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The number of Instagram photos for this activity</summary>
        public double? PhotoCount { get; set; }
        /// <summary>The number of personal records set during this activity</summary>
        public double? PrCount { get; set; }
        /// <summary>The raw data returned by the integration for this activity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.ClubsActivityRawProperty? Raw { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.ClubsActivityRawProperty Raw { get; set; }
#endif
        /// <summary>When the activity started (UTC) (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)</summary>
        public DateTimeOffset? StartAt { get; set; }
        /// <summary>The activity&apos;s relative effort score</summary>
        public double? SufferScore { get; set; }
        /// <summary>The timezone of the activity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The activity&apos;s total elevation gain, in meters</summary>
        public double? TotalElevationGain { get; set; }
        /// <summary>The activity type</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.ClubsActivityType? Type { get; set; }
        /// <summary>The last date that this activity was updated (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The activity&apos;s weighted average power output, in watts</summary>
        public double? WeightedAverageWatts { get; set; }
        /// <summary>The activity&apos;s workout type</summary>
        public double? WorkoutType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Models.ClubsActivity"/> and sets the default values.
        /// </summary>
        public ClubsActivity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.ClubsActivity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.ClubsActivity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Unified.OpenApiClient.Models.ClubsActivity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "achievement_count", n => { AchievementCount = n.GetDoubleValue(); } },
                { "athlete_count", n => { AthleteCount = n.GetDoubleValue(); } },
                { "athlete_id", n => { AthleteId = n.GetStringValue(); } },
                { "athlete_name", n => { AthleteName = n.GetStringValue(); } },
                { "average_cadence", n => { AverageCadence = n.GetDoubleValue(); } },
                { "average_heartrate", n => { AverageHeartrate = n.GetDoubleValue(); } },
                { "average_speed", n => { AverageSpeed = n.GetDoubleValue(); } },
                { "average_watts", n => { AverageWatts = n.GetDoubleValue(); } },
                { "calories", n => { Calories = n.GetDoubleValue(); } },
                { "comment_count", n => { CommentCount = n.GetDoubleValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "distance", n => { Distance = n.GetDoubleValue(); } },
                { "elapsed_time", n => { ElapsedTime = n.GetDoubleValue(); } },
                { "elevation_high", n => { ElevationHigh = n.GetDoubleValue(); } },
                { "elevation_low", n => { ElevationLow = n.GetDoubleValue(); } },
                { "group_id", n => { GroupId = n.GetStringValue(); } },
                { "has_heartrate", n => { HasHeartrate = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_commute", n => { IsCommute = n.GetBoolValue(); } },
                { "is_manual", n => { IsManual = n.GetBoolValue(); } },
                { "is_private", n => { IsPrivate = n.GetBoolValue(); } },
                { "is_trainer", n => { IsTrainer = n.GetBoolValue(); } },
                { "kilojoules", n => { Kilojoules = n.GetDoubleValue(); } },
                { "kudos_count", n => { KudosCount = n.GetDoubleValue(); } },
                { "map_polyline", n => { MapPolyline = n.GetStringValue(); } },
                { "map_summary_polyline", n => { MapSummaryPolyline = n.GetStringValue(); } },
                { "max_heartrate", n => { MaxHeartrate = n.GetDoubleValue(); } },
                { "max_speed", n => { MaxSpeed = n.GetDoubleValue(); } },
                { "max_watts", n => { MaxWatts = n.GetDoubleValue(); } },
                { "moving_time", n => { MovingTime = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "photo_count", n => { PhotoCount = n.GetDoubleValue(); } },
                { "pr_count", n => { PrCount = n.GetDoubleValue(); } },
                { "raw", n => { Raw = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.ClubsActivityRawProperty>(global::Soenneker.Unified.OpenApiClient.Models.ClubsActivityRawProperty.CreateFromDiscriminatorValue); } },
                { "start_at", n => { StartAt = n.GetDateTimeOffsetValue(); } },
                { "suffer_score", n => { SufferScore = n.GetDoubleValue(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "total_elevation_gain", n => { TotalElevationGain = n.GetDoubleValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.ClubsActivityType>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "weighted_average_watts", n => { WeightedAverageWatts = n.GetDoubleValue(); } },
                { "workout_type", n => { WorkoutType = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("achievement_count", AchievementCount);
            writer.WriteDoubleValue("athlete_count", AthleteCount);
            writer.WriteStringValue("athlete_id", AthleteId);
            writer.WriteStringValue("athlete_name", AthleteName);
            writer.WriteDoubleValue("average_cadence", AverageCadence);
            writer.WriteDoubleValue("average_heartrate", AverageHeartrate);
            writer.WriteDoubleValue("average_speed", AverageSpeed);
            writer.WriteDoubleValue("average_watts", AverageWatts);
            writer.WriteDoubleValue("calories", Calories);
            writer.WriteDoubleValue("comment_count", CommentCount);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteDoubleValue("distance", Distance);
            writer.WriteDoubleValue("elapsed_time", ElapsedTime);
            writer.WriteDoubleValue("elevation_high", ElevationHigh);
            writer.WriteDoubleValue("elevation_low", ElevationLow);
            writer.WriteStringValue("group_id", GroupId);
            writer.WriteBoolValue("has_heartrate", HasHeartrate);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_commute", IsCommute);
            writer.WriteBoolValue("is_manual", IsManual);
            writer.WriteBoolValue("is_private", IsPrivate);
            writer.WriteBoolValue("is_trainer", IsTrainer);
            writer.WriteDoubleValue("kilojoules", Kilojoules);
            writer.WriteDoubleValue("kudos_count", KudosCount);
            writer.WriteStringValue("map_polyline", MapPolyline);
            writer.WriteStringValue("map_summary_polyline", MapSummaryPolyline);
            writer.WriteDoubleValue("max_heartrate", MaxHeartrate);
            writer.WriteDoubleValue("max_speed", MaxSpeed);
            writer.WriteDoubleValue("max_watts", MaxWatts);
            writer.WriteDoubleValue("moving_time", MovingTime);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("photo_count", PhotoCount);
            writer.WriteDoubleValue("pr_count", PrCount);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.ClubsActivityRawProperty>("raw", Raw);
            writer.WriteDateTimeOffsetValue("start_at", StartAt);
            writer.WriteDoubleValue("suffer_score", SufferScore);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteDoubleValue("total_elevation_gain", TotalElevationGain);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.ClubsActivityType>("type", Type);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteDoubleValue("weighted_average_watts", WeightedAverageWatts);
            writer.WriteDoubleValue("workout_type", WorkoutType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
