// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Connection_permissions
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "accounting_account_read")]
        #pragma warning disable CS1591
        Accounting_account_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_account_write")]
        #pragma warning disable CS1591
        Accounting_account_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_transaction_read")]
        #pragma warning disable CS1591
        Accounting_transaction_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_transaction_write")]
        #pragma warning disable CS1591
        Accounting_transaction_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_journal_read")]
        #pragma warning disable CS1591
        Accounting_journal_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_journal_write")]
        #pragma warning disable CS1591
        Accounting_journal_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_invoice_read")]
        #pragma warning disable CS1591
        Accounting_invoice_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_invoice_write")]
        #pragma warning disable CS1591
        Accounting_invoice_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_bill_read")]
        #pragma warning disable CS1591
        Accounting_bill_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_bill_write")]
        #pragma warning disable CS1591
        Accounting_bill_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_creditmemo_read")]
        #pragma warning disable CS1591
        Accounting_creditmemo_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_creditmemo_write")]
        #pragma warning disable CS1591
        Accounting_creditmemo_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_contact_read")]
        #pragma warning disable CS1591
        Accounting_contact_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_contact_write")]
        #pragma warning disable CS1591
        Accounting_contact_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_expense_read")]
        #pragma warning disable CS1591
        Accounting_expense_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_expense_write")]
        #pragma warning disable CS1591
        Accounting_expense_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_taxrate_read")]
        #pragma warning disable CS1591
        Accounting_taxrate_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_taxrate_write")]
        #pragma warning disable CS1591
        Accounting_taxrate_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_organization_read")]
        #pragma warning disable CS1591
        Accounting_organization_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_order_read")]
        #pragma warning disable CS1591
        Accounting_order_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_order_write")]
        #pragma warning disable CS1591
        Accounting_order_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_purchaseorder_read")]
        #pragma warning disable CS1591
        Accounting_purchaseorder_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_purchaseorder_write")]
        #pragma warning disable CS1591
        Accounting_purchaseorder_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_salesorder_read")]
        #pragma warning disable CS1591
        Accounting_salesorder_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_salesorder_write")]
        #pragma warning disable CS1591
        Accounting_salesorder_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_report_read")]
        #pragma warning disable CS1591
        Accounting_report_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_report_write")]
        #pragma warning disable CS1591
        Accounting_report_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_trialbalance_read")]
        #pragma warning disable CS1591
        Accounting_trialbalance_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_trialbalance_write")]
        #pragma warning disable CS1591
        Accounting_trialbalance_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_profitloss_read")]
        #pragma warning disable CS1591
        Accounting_profitloss_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_profitloss_write")]
        #pragma warning disable CS1591
        Accounting_profitloss_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_balancesheet_read")]
        #pragma warning disable CS1591
        Accounting_balancesheet_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_balancesheet_write")]
        #pragma warning disable CS1591
        Accounting_balancesheet_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_category_read")]
        #pragma warning disable CS1591
        Accounting_category_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_category_write")]
        #pragma warning disable CS1591
        Accounting_category_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_payment_read")]
        #pragma warning disable CS1591
        Payment_payment_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_payment_write")]
        #pragma warning disable CS1591
        Payment_payment_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_cashflow_read")]
        #pragma warning disable CS1591
        Accounting_cashflow_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting_cashflow_write")]
        #pragma warning disable CS1591
        Accounting_cashflow_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_payout_read")]
        #pragma warning disable CS1591
        Payment_payout_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_refund_read")]
        #pragma warning disable CS1591
        Payment_refund_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_link_read")]
        #pragma warning disable CS1591
        Payment_link_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_link_write")]
        #pragma warning disable CS1591
        Payment_link_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_subscription_read")]
        #pragma warning disable CS1591
        Payment_subscription_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_subscription_write")]
        #pragma warning disable CS1591
        Payment_subscription_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_item_read")]
        #pragma warning disable CS1591
        Commerce_item_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_item_write")]
        #pragma warning disable CS1591
        Commerce_item_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_collection_read")]
        #pragma warning disable CS1591
        Commerce_collection_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_collection_write")]
        #pragma warning disable CS1591
        Commerce_collection_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_inventory_read")]
        #pragma warning disable CS1591
        Commerce_inventory_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_inventory_write")]
        #pragma warning disable CS1591
        Commerce_inventory_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_location_read")]
        #pragma warning disable CS1591
        Commerce_location_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_location_write")]
        #pragma warning disable CS1591
        Commerce_location_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_review_read")]
        #pragma warning disable CS1591
        Commerce_review_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_review_write")]
        #pragma warning disable CS1591
        Commerce_review_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_saleschannel_read")]
        #pragma warning disable CS1591
        Commerce_saleschannel_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_saleschannel_write")]
        #pragma warning disable CS1591
        Commerce_saleschannel_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_itemvariant_read")]
        #pragma warning disable CS1591
        Commerce_itemvariant_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_itemvariant_write")]
        #pragma warning disable CS1591
        Commerce_itemvariant_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_reservation_read")]
        #pragma warning disable CS1591
        Commerce_reservation_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_reservation_write")]
        #pragma warning disable CS1591
        Commerce_reservation_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_availability_read")]
        #pragma warning disable CS1591
        Commerce_availability_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "commerce_availability_write")]
        #pragma warning disable CS1591
        Commerce_availability_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_package_read")]
        #pragma warning disable CS1591
        Verification_package_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_request_read")]
        #pragma warning disable CS1591
        Verification_request_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_request_write")]
        #pragma warning disable CS1591
        Verification_request_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "assessment_package_read")]
        #pragma warning disable CS1591
        Assessment_package_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "assessment_package_write")]
        #pragma warning disable CS1591
        Assessment_package_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "assessment_order_write")]
        #pragma warning disable CS1591
        Assessment_order_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_activity_read")]
        #pragma warning disable CS1591
        Ats_activity_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_activity_write")]
        #pragma warning disable CS1591
        Ats_activity_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_application_read")]
        #pragma warning disable CS1591
        Ats_application_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_application_write")]
        #pragma warning disable CS1591
        Ats_application_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_applicationstatus_read")]
        #pragma warning disable CS1591
        Ats_applicationstatus_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_candidate_read")]
        #pragma warning disable CS1591
        Ats_candidate_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_candidate_write")]
        #pragma warning disable CS1591
        Ats_candidate_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_interview_read")]
        #pragma warning disable CS1591
        Ats_interview_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_interview_write")]
        #pragma warning disable CS1591
        Ats_interview_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_job_read")]
        #pragma warning disable CS1591
        Ats_job_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_job_write")]
        #pragma warning disable CS1591
        Ats_job_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_company_read")]
        #pragma warning disable CS1591
        Ats_company_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_company_write")]
        #pragma warning disable CS1591
        Ats_company_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_document_read")]
        #pragma warning disable CS1591
        Ats_document_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_document_write")]
        #pragma warning disable CS1591
        Ats_document_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_scorecard_read")]
        #pragma warning disable CS1591
        Ats_scorecard_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ats_scorecard_write")]
        #pragma warning disable CS1591
        Ats_scorecard_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_company_read")]
        #pragma warning disable CS1591
        Crm_company_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_company_write")]
        #pragma warning disable CS1591
        Crm_company_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_contact_read")]
        #pragma warning disable CS1591
        Crm_contact_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_contact_write")]
        #pragma warning disable CS1591
        Crm_contact_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_deal_read")]
        #pragma warning disable CS1591
        Crm_deal_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_deal_write")]
        #pragma warning disable CS1591
        Crm_deal_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_event_read")]
        #pragma warning disable CS1591
        Crm_event_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_event_write")]
        #pragma warning disable CS1591
        Crm_event_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_lead_read")]
        #pragma warning disable CS1591
        Crm_lead_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_lead_write")]
        #pragma warning disable CS1591
        Crm_lead_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_pipeline_read")]
        #pragma warning disable CS1591
        Crm_pipeline_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_pipeline_write")]
        #pragma warning disable CS1591
        Crm_pipeline_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "martech_list_read")]
        #pragma warning disable CS1591
        Martech_list_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "martech_list_write")]
        #pragma warning disable CS1591
        Martech_list_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "martech_member_read")]
        #pragma warning disable CS1591
        Martech_member_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "martech_member_write")]
        #pragma warning disable CS1591
        Martech_member_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "martech_campaign_read")]
        #pragma warning disable CS1591
        Martech_campaign_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "martech_campaign_write")]
        #pragma warning disable CS1591
        Martech_campaign_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "martech_report_read")]
        #pragma warning disable CS1591
        Martech_report_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "martech_report_write")]
        #pragma warning disable CS1591
        Martech_report_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticketing_customer_read")]
        #pragma warning disable CS1591
        Ticketing_customer_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticketing_customer_write")]
        #pragma warning disable CS1591
        Ticketing_customer_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticketing_ticket_read")]
        #pragma warning disable CS1591
        Ticketing_ticket_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticketing_ticket_write")]
        #pragma warning disable CS1591
        Ticketing_ticket_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticketing_note_read")]
        #pragma warning disable CS1591
        Ticketing_note_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticketing_note_write")]
        #pragma warning disable CS1591
        Ticketing_note_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticketing_category_read")]
        #pragma warning disable CS1591
        Ticketing_category_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticketing_category_write")]
        #pragma warning disable CS1591
        Ticketing_category_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_employee_read")]
        #pragma warning disable CS1591
        Hris_employee_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_employee_write")]
        #pragma warning disable CS1591
        Hris_employee_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_group_read")]
        #pragma warning disable CS1591
        Hris_group_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_group_write")]
        #pragma warning disable CS1591
        Hris_group_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_payslip_read")]
        #pragma warning disable CS1591
        Hris_payslip_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_payslip_write")]
        #pragma warning disable CS1591
        Hris_payslip_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_timeoff_read")]
        #pragma warning disable CS1591
        Hris_timeoff_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_timeoff_write")]
        #pragma warning disable CS1591
        Hris_timeoff_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_timeshift_read")]
        #pragma warning disable CS1591
        Hris_timeshift_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_timeshift_write")]
        #pragma warning disable CS1591
        Hris_timeshift_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_company_read")]
        #pragma warning disable CS1591
        Hris_company_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_company_write")]
        #pragma warning disable CS1591
        Hris_company_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_location_read")]
        #pragma warning disable CS1591
        Hris_location_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_location_write")]
        #pragma warning disable CS1591
        Hris_location_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_device_read")]
        #pragma warning disable CS1591
        Hris_device_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_device_write")]
        #pragma warning disable CS1591
        Hris_device_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_deduction_read")]
        #pragma warning disable CS1591
        Hris_deduction_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_deduction_write")]
        #pragma warning disable CS1591
        Hris_deduction_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_benefit_read")]
        #pragma warning disable CS1591
        Hris_benefit_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_benefit_write")]
        #pragma warning disable CS1591
        Hris_benefit_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_bankaccount_read")]
        #pragma warning disable CS1591
        Hris_bankaccount_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "hris_bankaccount_write")]
        #pragma warning disable CS1591
        Hris_bankaccount_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "uc_call_read")]
        #pragma warning disable CS1591
        Uc_call_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "uc_contact_read")]
        #pragma warning disable CS1591
        Uc_contact_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "uc_contact_write")]
        #pragma warning disable CS1591
        Uc_contact_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "uc_comment_read")]
        #pragma warning disable CS1591
        Uc_comment_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "uc_comment_write")]
        #pragma warning disable CS1591
        Uc_comment_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "uc_recording_read")]
        #pragma warning disable CS1591
        Uc_recording_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "storage_file_read")]
        #pragma warning disable CS1591
        Storage_file_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "storage_file_write")]
        #pragma warning disable CS1591
        Storage_file_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "webhook")]
        #pragma warning disable CS1591
        Webhook,
        #pragma warning restore CS1591
        [EnumMember(Value = "genai_model_read")]
        #pragma warning disable CS1591
        Genai_model_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "genai_prompt_read")]
        #pragma warning disable CS1591
        Genai_prompt_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "genai_prompt_write")]
        #pragma warning disable CS1591
        Genai_prompt_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "genai_embedding_read")]
        #pragma warning disable CS1591
        Genai_embedding_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "genai_embedding_write")]
        #pragma warning disable CS1591
        Genai_embedding_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "messaging_message_read")]
        #pragma warning disable CS1591
        Messaging_message_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "messaging_message_write")]
        #pragma warning disable CS1591
        Messaging_message_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "messaging_channel_read")]
        #pragma warning disable CS1591
        Messaging_channel_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "messaging_event_read")]
        #pragma warning disable CS1591
        Messaging_event_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "messaging_event_write")]
        #pragma warning disable CS1591
        Messaging_event_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "kms_space_read")]
        #pragma warning disable CS1591
        Kms_space_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "kms_space_write")]
        #pragma warning disable CS1591
        Kms_space_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "kms_page_read")]
        #pragma warning disable CS1591
        Kms_page_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "kms_page_write")]
        #pragma warning disable CS1591
        Kms_page_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "kms_comment_read")]
        #pragma warning disable CS1591
        Kms_comment_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "kms_comment_write")]
        #pragma warning disable CS1591
        Kms_comment_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "task_project_read")]
        #pragma warning disable CS1591
        Task_project_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "task_project_write")]
        #pragma warning disable CS1591
        Task_project_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "task_task_read")]
        #pragma warning disable CS1591
        Task_task_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "task_task_write")]
        #pragma warning disable CS1591
        Task_task_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "task_change_read")]
        #pragma warning disable CS1591
        Task_change_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "task_comment_read")]
        #pragma warning disable CS1591
        Task_comment_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "task_comment_write")]
        #pragma warning disable CS1591
        Task_comment_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "scim_users_read")]
        #pragma warning disable CS1591
        Scim_users_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "scim_users_write")]
        #pragma warning disable CS1591
        Scim_users_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "scim_groups_read")]
        #pragma warning disable CS1591
        Scim_groups_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "scim_groups_write")]
        #pragma warning disable CS1591
        Scim_groups_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_course_read")]
        #pragma warning disable CS1591
        Lms_course_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_course_write")]
        #pragma warning disable CS1591
        Lms_course_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_class_read")]
        #pragma warning disable CS1591
        Lms_class_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_class_write")]
        #pragma warning disable CS1591
        Lms_class_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_student_read")]
        #pragma warning disable CS1591
        Lms_student_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_student_write")]
        #pragma warning disable CS1591
        Lms_student_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_instructor_read")]
        #pragma warning disable CS1591
        Lms_instructor_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_instructor_write")]
        #pragma warning disable CS1591
        Lms_instructor_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_content_read")]
        #pragma warning disable CS1591
        Lms_content_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_content_write")]
        #pragma warning disable CS1591
        Lms_content_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_collection_read")]
        #pragma warning disable CS1591
        Lms_collection_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_collection_write")]
        #pragma warning disable CS1591
        Lms_collection_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_activity_read")]
        #pragma warning disable CS1591
        Lms_activity_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "lms_activity_write")]
        #pragma warning disable CS1591
        Lms_activity_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_organization_read")]
        #pragma warning disable CS1591
        Repo_organization_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_organization_write")]
        #pragma warning disable CS1591
        Repo_organization_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_repository_read")]
        #pragma warning disable CS1591
        Repo_repository_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_repository_write")]
        #pragma warning disable CS1591
        Repo_repository_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_branch_read")]
        #pragma warning disable CS1591
        Repo_branch_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_branch_write")]
        #pragma warning disable CS1591
        Repo_branch_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_commit_read")]
        #pragma warning disable CS1591
        Repo_commit_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_commit_write")]
        #pragma warning disable CS1591
        Repo_commit_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_pullrequest_read")]
        #pragma warning disable CS1591
        Repo_pullrequest_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_pullrequest_write")]
        #pragma warning disable CS1591
        Repo_pullrequest_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "metadata_metadata_read")]
        #pragma warning disable CS1591
        Metadata_metadata_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "metadata_metadata_write")]
        #pragma warning disable CS1591
        Metadata_metadata_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_calendar_read")]
        #pragma warning disable CS1591
        Calendar_calendar_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_calendar_write")]
        #pragma warning disable CS1591
        Calendar_calendar_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_event_read")]
        #pragma warning disable CS1591
        Calendar_event_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_event_write")]
        #pragma warning disable CS1591
        Calendar_event_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_busy_read")]
        #pragma warning disable CS1591
        Calendar_busy_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_link_read")]
        #pragma warning disable CS1591
        Calendar_link_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_link_write")]
        #pragma warning disable CS1591
        Calendar_link_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_recording_read")]
        #pragma warning disable CS1591
        Calendar_recording_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_recording_write")]
        #pragma warning disable CS1591
        Calendar_recording_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_webinar_read")]
        #pragma warning disable CS1591
        Calendar_webinar_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar_webinar_write")]
        #pragma warning disable CS1591
        Calendar_webinar_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "enrich_person_read")]
        #pragma warning disable CS1591
        Enrich_person_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "enrich_company_read")]
        #pragma warning disable CS1591
        Enrich_company_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_ad_read")]
        #pragma warning disable CS1591
        Ads_ad_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_ad_write")]
        #pragma warning disable CS1591
        Ads_ad_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_campaign_read")]
        #pragma warning disable CS1591
        Ads_campaign_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_campaign_write")]
        #pragma warning disable CS1591
        Ads_campaign_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_group_read")]
        #pragma warning disable CS1591
        Ads_group_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_group_write")]
        #pragma warning disable CS1591
        Ads_group_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_report_read")]
        #pragma warning disable CS1591
        Ads_report_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_organization_read")]
        #pragma warning disable CS1591
        Ads_organization_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_organization_write")]
        #pragma warning disable CS1591
        Ads_organization_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_creative_read")]
        #pragma warning disable CS1591
        Ads_creative_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_creative_write")]
        #pragma warning disable CS1591
        Ads_creative_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_insertionorder_read")]
        #pragma warning disable CS1591
        Ads_insertionorder_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_insertionorder_write")]
        #pragma warning disable CS1591
        Ads_insertionorder_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_target_read")]
        #pragma warning disable CS1591
        Ads_target_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "ads_promoted_read")]
        #pragma warning disable CS1591
        Ads_promoted_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "forms_form_read")]
        #pragma warning disable CS1591
        Forms_form_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "forms_form_write")]
        #pragma warning disable CS1591
        Forms_form_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "forms_submission_read")]
        #pragma warning disable CS1591
        Forms_submission_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "forms_submission_write")]
        #pragma warning disable CS1591
        Forms_submission_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_shipment_read")]
        #pragma warning disable CS1591
        Shipping_shipment_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_shipment_write")]
        #pragma warning disable CS1591
        Shipping_shipment_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_label_read")]
        #pragma warning disable CS1591
        Shipping_label_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_label_write")]
        #pragma warning disable CS1591
        Shipping_label_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_tracking_read")]
        #pragma warning disable CS1591
        Shipping_tracking_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_rate_read")]
        #pragma warning disable CS1591
        Shipping_rate_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_carrier_read")]
        #pragma warning disable CS1591
        Shipping_carrier_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "signing_document_read")]
        #pragma warning disable CS1591
        Signing_document_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "signing_document_write")]
        #pragma warning disable CS1591
        Signing_document_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "signing_signatory_read")]
        #pragma warning disable CS1591
        Signing_signatory_read,
        #pragma warning restore CS1591
        [EnumMember(Value = "signing_signatory_write")]
        #pragma warning disable CS1591
        Signing_signatory_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "signing_template_read")]
        #pragma warning disable CS1591
        Signing_template_read,
        #pragma warning restore CS1591
    }
}
