// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateCommerceInventory2FieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "item_id")]
        #pragma warning disable CS1591
        ItemId,
        #pragma warning restore CS1591
        [EnumMember(Value = "item_variant_id")]
        #pragma warning disable CS1591
        ItemVariantId,
        #pragma warning restore CS1591
        [EnumMember(Value = "item_option_id")]
        #pragma warning disable CS1591
        ItemOptionId,
        #pragma warning restore CS1591
        [EnumMember(Value = "location_id")]
        #pragma warning disable CS1591
        LocationId,
        #pragma warning restore CS1591
        [EnumMember(Value = "available")]
        #pragma warning disable CS1591
        Available,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
