// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateAtsJobFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "recruiter_ids")]
        #pragma warning disable CS1591
        RecruiterIds,
        #pragma warning restore CS1591
        [EnumMember(Value = "hiring_manager_ids")]
        #pragma warning disable CS1591
        HiringManagerIds,
        #pragma warning restore CS1591
        [EnumMember(Value = "hiring_managers")]
        #pragma warning disable CS1591
        HiringManagers,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed_at")]
        #pragma warning disable CS1591
        ClosedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "addresses")]
        #pragma warning disable CS1591
        Addresses,
        #pragma warning restore CS1591
        [EnumMember(Value = "compensation")]
        #pragma warning disable CS1591
        Compensation,
        #pragma warning restore CS1591
        [EnumMember(Value = "employment_type")]
        #pragma warning disable CS1591
        EmploymentType,
        #pragma warning restore CS1591
        [EnumMember(Value = "remote")]
        #pragma warning disable CS1591
        Remote,
        #pragma warning restore CS1591
        [EnumMember(Value = "language_locale")]
        #pragma warning disable CS1591
        LanguageLocale,
        #pragma warning restore CS1591
        [EnumMember(Value = "public_job_urls")]
        #pragma warning disable CS1591
        PublicJobUrls,
        #pragma warning restore CS1591
        [EnumMember(Value = "number_of_openings")]
        #pragma warning disable CS1591
        NumberOfOpenings,
        #pragma warning restore CS1591
        [EnumMember(Value = "company_id")]
        #pragma warning disable CS1591
        CompanyId,
        #pragma warning restore CS1591
        [EnumMember(Value = "questions")]
        #pragma warning disable CS1591
        Questions,
        #pragma warning restore CS1591
        [EnumMember(Value = "postings")]
        #pragma warning disable CS1591
        Postings,
        #pragma warning restore CS1591
        [EnumMember(Value = "groups")]
        #pragma warning disable CS1591
        Groups,
        #pragma warning restore CS1591
        [EnumMember(Value = "openings")]
        #pragma warning disable CS1591
        Openings,
        #pragma warning restore CS1591
        [EnumMember(Value = "minimum_experience_years")]
        #pragma warning disable CS1591
        MinimumExperienceYears,
        #pragma warning restore CS1591
        [EnumMember(Value = "minimum_degree")]
        #pragma warning disable CS1591
        MinimumDegree,
        #pragma warning restore CS1591
        [EnumMember(Value = "skills")]
        #pragma warning disable CS1591
        Skills,
        #pragma warning restore CS1591
        [EnumMember(Value = "metadata")]
        #pragma warning disable CS1591
        Metadata,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_id")]
        #pragma warning disable CS1591
        UserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "industry")]
        #pragma warning disable CS1591
        Industry,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
