// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateAdsGroupFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent_id")]
        #pragma warning disable CS1591
        ParentId,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign_id")]
        #pragma warning disable CS1591
        CampaignId,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_id")]
        #pragma warning disable CS1591
        OrganizationId,
        #pragma warning restore CS1591
        [EnumMember(Value = "insertionorder_id")]
        #pragma warning disable CS1591
        InsertionorderId,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "targeting")]
        #pragma warning disable CS1591
        Targeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "bid_amount")]
        #pragma warning disable CS1591
        BidAmount,
        #pragma warning restore CS1591
        [EnumMember(Value = "bid_strategy")]
        #pragma warning disable CS1591
        BidStrategy,
        #pragma warning restore CS1591
        [EnumMember(Value = "budget_amount")]
        #pragma warning disable CS1591
        BudgetAmount,
        #pragma warning restore CS1591
        [EnumMember(Value = "budget_period")]
        #pragma warning disable CS1591
        BudgetPeriod,
        #pragma warning restore CS1591
        [EnumMember(Value = "budget_allocation_type")]
        #pragma warning disable CS1591
        BudgetAllocationType,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_at")]
        #pragma warning disable CS1591
        StartAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_at")]
        #pragma warning disable CS1591
        EndAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "budget_unit")]
        #pragma warning disable CS1591
        BudgetUnit,
        #pragma warning restore CS1591
        [EnumMember(Value = "budget_max_amount")]
        #pragma warning disable CS1591
        BudgetMaxAmount,
        #pragma warning restore CS1591
        [EnumMember(Value = "type")]
        #pragma warning disable CS1591
        Type,
        #pragma warning restore CS1591
        [EnumMember(Value = "has_eu_political_ads")]
        #pragma warning disable CS1591
        HasEuPoliticalAds,
        #pragma warning restore CS1591
        [EnumMember(Value = "pacing")]
        #pragma warning disable CS1591
        Pacing,
        #pragma warning restore CS1591
        [EnumMember(Value = "frequency_cap")]
        #pragma warning disable CS1591
        FrequencyCap,
        #pragma warning restore CS1591
        [EnumMember(Value = "creative_ids")]
        #pragma warning disable CS1591
        CreativeIds,
        #pragma warning restore CS1591
        [EnumMember(Value = "optimization_goal")]
        #pragma warning disable CS1591
        OptimizationGoal,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing_event")]
        #pragma warning disable CS1591
        BillingEvent,
        #pragma warning restore CS1591
        [EnumMember(Value = "currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "promoted")]
        #pragma warning disable CS1591
        Promoted,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
