// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetAnalyticsEventFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "event_type")]
        #pragma warning disable CS1591
        EventType,
        #pragma warning restore CS1591
        [EnumMember(Value = "visitor_id")]
        #pragma warning disable CS1591
        VisitorId,
        #pragma warning restore CS1591
        [EnumMember(Value = "property_id")]
        #pragma warning disable CS1591
        PropertyId,
        #pragma warning restore CS1591
        [EnumMember(Value = "session_id")]
        #pragma warning disable CS1591
        SessionId,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_url")]
        #pragma warning disable CS1591
        PageUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_title")]
        #pragma warning disable CS1591
        PageTitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_referrer")]
        #pragma warning disable CS1591
        PageReferrer,
        #pragma warning restore CS1591
        [EnumMember(Value = "device")]
        #pragma warning disable CS1591
        Device,
        #pragma warning restore CS1591
        [EnumMember(Value = "browser")]
        #pragma warning disable CS1591
        Browser,
        #pragma warning restore CS1591
        [EnumMember(Value = "os")]
        #pragma warning disable CS1591
        Os,
        #pragma warning restore CS1591
        [EnumMember(Value = "country")]
        #pragma warning disable CS1591
        Country,
        #pragma warning restore CS1591
        [EnumMember(Value = "country_code")]
        #pragma warning disable CS1591
        CountryCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "region")]
        #pragma warning disable CS1591
        Region,
        #pragma warning restore CS1591
        [EnumMember(Value = "city")]
        #pragma warning disable CS1591
        City,
        #pragma warning restore CS1591
        [EnumMember(Value = "metadata")]
        #pragma warning disable CS1591
        Metadata,
        #pragma warning restore CS1591
        [EnumMember(Value = "value")]
        #pragma warning disable CS1591
        Value,
        #pragma warning restore CS1591
        [EnumMember(Value = "currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_source")]
        #pragma warning disable CS1591
        UtmSource,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_medium")]
        #pragma warning disable CS1591
        UtmMedium,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_campaign")]
        #pragma warning disable CS1591
        UtmCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_term")]
        #pragma warning disable CS1591
        UtmTerm,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_content")]
        #pragma warning disable CS1591
        UtmContent,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
