// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetAccountingTaxrateFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "rate")]
        #pragma warning disable CS1591
        Rate,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_active")]
        #pragma warning disable CS1591
        IsActive,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_id")]
        #pragma warning disable CS1591
        OrganizationId,
        #pragma warning restore CS1591
        [EnumMember(Value = "metadata")]
        #pragma warning disable CS1591
        Metadata,
        #pragma warning restore CS1591
        [EnumMember(Value = "effective_rate")]
        #pragma warning disable CS1591
        EffectiveRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "total_rate")]
        #pragma warning disable CS1591
        TotalRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "components")]
        #pragma warning disable CS1591
        Components,
        #pragma warning restore CS1591
        [EnumMember(Value = "type")]
        #pragma warning disable CS1591
        Type,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_compound")]
        #pragma warning disable CS1591
        IsCompound,
        #pragma warning restore CS1591
        [EnumMember(Value = "country")]
        #pragma warning disable CS1591
        Country,
        #pragma warning restore CS1591
        [EnumMember(Value = "region")]
        #pragma warning disable CS1591
        Region,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
