// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetAccountingOrganization2FieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "legal_name")]
        #pragma warning disable CS1591
        LegalName,
        #pragma warning restore CS1591
        [EnumMember(Value = "currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "address")]
        #pragma warning disable CS1591
        Address,
        #pragma warning restore CS1591
        [EnumMember(Value = "tax_number")]
        #pragma warning disable CS1591
        TaxNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "timezone")]
        #pragma warning disable CS1591
        Timezone,
        #pragma warning restore CS1591
        [EnumMember(Value = "website")]
        #pragma warning disable CS1591
        Website,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent_id")]
        #pragma warning disable CS1591
        ParentId,
        #pragma warning restore CS1591
        [EnumMember(Value = "fiscal_year_end_month")]
        #pragma warning disable CS1591
        FiscalYearEndMonth,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_code")]
        #pragma warning disable CS1591
        OrganizationCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
