// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetClubsLocationFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "group_id")]
        #pragma warning disable CS1591
        GroupId,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "address")]
        #pragma warning disable CS1591
        Address,
        #pragma warning restore CS1591
        [EnumMember(Value = "latitude")]
        #pragma warning disable CS1591
        Latitude,
        #pragma warning restore CS1591
        [EnumMember(Value = "longitude")]
        #pragma warning disable CS1591
        Longitude,
        #pragma warning restore CS1591
        [EnumMember(Value = "telephone")]
        #pragma warning disable CS1591
        Telephone,
        #pragma warning restore CS1591
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
