// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetDatastoreTable2FieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "database_id")]
        #pragma warning disable CS1591
        DatabaseId,
        #pragma warning restore CS1591
        [EnumMember(Value = "fields")]
        #pragma warning disable CS1591
        Fields,
        #pragma warning restore CS1591
        [EnumMember(Value = "relationships")]
        #pragma warning disable CS1591
        Relationships,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_url")]
        #pragma warning disable CS1591
        WebUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent_id")]
        #pragma warning disable CS1591
        ParentId,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
