// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetHrisBankaccountFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_id")]
        #pragma warning disable CS1591
        UserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "company_id")]
        #pragma warning disable CS1591
        CompanyId,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_type")]
        #pragma warning disable CS1591
        AccountType,
        #pragma warning restore CS1591
        [EnumMember(Value = "bank_name")]
        #pragma warning disable CS1591
        BankName,
        #pragma warning restore CS1591
        [EnumMember(Value = "routing_number")]
        #pragma warning disable CS1591
        RoutingNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_number")]
        #pragma warning disable CS1591
        AccountNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_number_last4")]
        #pragma warning disable CS1591
        AccountNumberLast4,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_primary")]
        #pragma warning disable CS1591
        IsPrimary,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
