// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum HrisPayslipDetailType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "EARNING_SALARY")]
        #pragma warning disable CS1591
        EarningSalary,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_OVERTIME")]
        #pragma warning disable CS1591
        EarningOvertime,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_TIP")]
        #pragma warning disable CS1591
        EarningTip,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_BONUS")]
        #pragma warning disable CS1591
        EarningBonus,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_COMMISSION")]
        #pragma warning disable CS1591
        EarningCommission,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_ADJUSTMENT")]
        #pragma warning disable CS1591
        EarningAdjustment,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING")]
        #pragma warning disable CS1591
        Earning,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION")]
        #pragma warning disable CS1591
        PretaxDeduction,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION_HEALTH_INSURANCE")]
        #pragma warning disable CS1591
        PretaxDeductionHealthInsurance,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION_RETIREMENT")]
        #pragma warning disable CS1591
        PretaxDeductionRetirement,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION_HRA")]
        #pragma warning disable CS1591
        PretaxDeductionHra,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAX_FEDERAL")]
        #pragma warning disable CS1591
        TaxFederal,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAX_REGION")]
        #pragma warning disable CS1591
        TaxRegion,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAX_LOCAL")]
        #pragma warning disable CS1591
        TaxLocal,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTTAX_BENEFIT")]
        #pragma warning disable CS1591
        PosttaxBenefit,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTTAX_GARNISHMENT")]
        #pragma warning disable CS1591
        PosttaxGarnishment,
        #pragma warning restore CS1591
        [EnumMember(Value = "REIMBURSEMENT")]
        #pragma warning disable CS1591
        Reimbursement,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_REGULAR")]
        #pragma warning disable CS1591
        EarningRegular,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_DOUBLE_OVERTIME")]
        #pragma warning disable CS1591
        EarningDoubleOvertime,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_PTO")]
        #pragma warning disable CS1591
        EarningPto,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_SICK")]
        #pragma warning disable CS1591
        EarningSick,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_HOLIDAY")]
        #pragma warning disable CS1591
        EarningHoliday,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_SEVERANCE")]
        #pragma warning disable CS1591
        EarningSeverance,
        #pragma warning restore CS1591
        [EnumMember(Value = "EARNING_REIMBURSEMENT")]
        #pragma warning disable CS1591
        EarningReimbursement,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAX_SOCIAL_SECURITY")]
        #pragma warning disable CS1591
        TaxSocialSecurity,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAX_MEDICARE")]
        #pragma warning disable CS1591
        TaxMedicare,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAX_UNEMPLOYMENT")]
        #pragma warning disable CS1591
        TaxUnemployment,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAX_EMPLOYER")]
        #pragma warning disable CS1591
        TaxEmployer,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION_HSA")]
        #pragma warning disable CS1591
        PretaxDeductionHsa,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION_FSA")]
        #pragma warning disable CS1591
        PretaxDeductionFsa,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION_DEPENDENT_CARE")]
        #pragma warning disable CS1591
        PretaxDeductionDependentCare,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION_COMMUTER")]
        #pragma warning disable CS1591
        PretaxDeductionCommuter,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION_DENTAL")]
        #pragma warning disable CS1591
        PretaxDeductionDental,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRETAX_DEDUCTION_VISION")]
        #pragma warning disable CS1591
        PretaxDeductionVision,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTTAX_DEDUCTION")]
        #pragma warning disable CS1591
        PosttaxDeduction,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTTAX_RETIREMENT_ROTH")]
        #pragma warning disable CS1591
        PosttaxRetirementRoth,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTTAX_LOAN_REPAYMENT")]
        #pragma warning disable CS1591
        PosttaxLoanRepayment,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMPLOYER_CONTRIBUTION")]
        #pragma warning disable CS1591
        EmployerContribution,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENSION")]
        #pragma warning disable CS1591
        Pension,
        #pragma warning restore CS1591
    }
}
