// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum HrisEmployee_employment_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FULL_TIME")]
        #pragma warning disable CS1591
        FULL_TIME,
        #pragma warning restore CS1591
        [EnumMember(Value = "PART_TIME")]
        #pragma warning disable CS1591
        PART_TIME,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTRACTOR")]
        #pragma warning disable CS1591
        CONTRACTOR,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTERN")]
        #pragma warning disable CS1591
        INTERN,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONSULTANT")]
        #pragma warning disable CS1591
        CONSULTANT,
        #pragma warning restore CS1591
        [EnumMember(Value = "VOLUNTEER")]
        #pragma warning disable CS1591
        VOLUNTEER,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASUAL")]
        #pragma warning disable CS1591
        CASUAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEASONAL")]
        #pragma warning disable CS1591
        SEASONAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "FREELANCE")]
        #pragma warning disable CS1591
        FREELANCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
    }
}
