// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch2"/>, <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch3"/>, <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch4"/>, <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch5"/>, <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IntegrationSandbox : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch2? IntegrationSandboxBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch2 IntegrationSandboxBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch3? IntegrationSandboxBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch3 IntegrationSandboxBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch4? IntegrationSandboxBranch4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch4 IntegrationSandboxBranch4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch5? IntegrationSandboxBranch5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch5 IntegrationSandboxBranch5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxMember1? IntegrationSandboxMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxMember1 IntegrationSandboxMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandbox"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandbox CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandbox();
            result.IntegrationSandboxBranch2 = new global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch2();
            result.IntegrationSandboxBranch3 = new global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch3();
            result.IntegrationSandboxBranch4 = new global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch4();
            result.IntegrationSandboxBranch5 = new global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch5();
            result.IntegrationSandboxMember1 = new global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxMember1();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(IntegrationSandboxBranch2 != null || IntegrationSandboxBranch3 != null || IntegrationSandboxBranch4 != null || IntegrationSandboxBranch5 != null || IntegrationSandboxMember1 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(IntegrationSandboxBranch2, IntegrationSandboxBranch3, IntegrationSandboxBranch4, IntegrationSandboxBranch5, IntegrationSandboxMember1);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.IntegrationSandboxBranch2>(null, IntegrationSandboxBranch2, IntegrationSandboxBranch3, IntegrationSandboxBranch4, IntegrationSandboxBranch5, IntegrationSandboxMember1);
        }
    }
}
#pragma warning restore CS0618
