// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch2"/>, <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch3"/>, <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch4"/>, <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch5"/>, <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KmsPageMetadataValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch2? KmsPageMetadataValueBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch2 KmsPageMetadataValueBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch3? KmsPageMetadataValueBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch3 KmsPageMetadataValueBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch4? KmsPageMetadataValueBranch4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch4 KmsPageMetadataValueBranch4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch5? KmsPageMetadataValueBranch5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch5 KmsPageMetadataValueBranch5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueMember1? KmsPageMetadataValueMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueMember1 KmsPageMetadataValueMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValue();
            result.KmsPageMetadataValueBranch2 = new global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch2();
            result.KmsPageMetadataValueBranch3 = new global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch3();
            result.KmsPageMetadataValueBranch4 = new global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch4();
            result.KmsPageMetadataValueBranch5 = new global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch5();
            result.KmsPageMetadataValueMember1 = new global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueMember1();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(KmsPageMetadataValueBranch2 != null || KmsPageMetadataValueBranch3 != null || KmsPageMetadataValueBranch4 != null || KmsPageMetadataValueBranch5 != null || KmsPageMetadataValueMember1 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(KmsPageMetadataValueBranch2, KmsPageMetadataValueBranch3, KmsPageMetadataValueBranch4, KmsPageMetadataValueBranch5, KmsPageMetadataValueMember1);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.KmsPageMetadataValueBranch2>(null, KmsPageMetadataValueBranch2, KmsPageMetadataValueBranch3, KmsPageMetadataValueBranch4, KmsPageMetadataValueBranch5, KmsPageMetadataValueMember1);
        }
    }
}
#pragma warning restore CS0618
