// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListUcScorecardsFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "call_id")]
        #pragma warning disable CS1591
        CallId,
        #pragma warning restore CS1591
        [EnumMember(Value = "scorecardtemplate_id")]
        #pragma warning disable CS1591
        ScorecardtemplateId,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_id")]
        #pragma warning disable CS1591
        UserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "reviewer_user_id")]
        #pragma warning disable CS1591
        ReviewerUserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "reviewed_at")]
        #pragma warning disable CS1591
        ReviewedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "score")]
        #pragma warning disable CS1591
        Score,
        #pragma warning restore CS1591
        [EnumMember(Value = "questions")]
        #pragma warning disable CS1591
        Questions,
        #pragma warning restore CS1591
        [EnumMember(Value = "metadata")]
        #pragma warning disable CS1591
        Metadata,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
