// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListPerformanceFeedbacksFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_id")]
        #pragma warning disable CS1591
        UserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "author_user_id")]
        #pragma warning disable CS1591
        AuthorUserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "type")]
        #pragma warning disable CS1591
        Type,
        #pragma warning restore CS1591
        [EnumMember(Value = "message")]
        #pragma warning disable CS1591
        Message,
        #pragma warning restore CS1591
        [EnumMember(Value = "tags")]
        #pragma warning disable CS1591
        Tags,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_visible")]
        #pragma warning disable CS1591
        IsVisible,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
