// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListUcRecordings2FieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_at")]
        #pragma warning disable CS1591
        StartAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_at")]
        #pragma warning disable CS1591
        EndAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "expires_at")]
        #pragma warning disable CS1591
        ExpiresAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "call_id")]
        #pragma warning disable CS1591
        CallId,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_url")]
        #pragma warning disable CS1591
        WebUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "contact_id")]
        #pragma warning disable CS1591
        ContactId,
        #pragma warning restore CS1591
        [EnumMember(Value = "contact_name")]
        #pragma warning disable CS1591
        ContactName,
        #pragma warning restore CS1591
        [EnumMember(Value = "contact_phone")]
        #pragma warning disable CS1591
        ContactPhone,
        #pragma warning restore CS1591
        [EnumMember(Value = "contacts")]
        #pragma warning disable CS1591
        Contacts,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_id")]
        #pragma warning disable CS1591
        UserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "media")]
        #pragma warning disable CS1591
        Media,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_name")]
        #pragma warning disable CS1591
        UserName,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_phone")]
        #pragma warning disable CS1591
        UserPhone,
        #pragma warning restore CS1591
        [EnumMember(Value = "type")]
        #pragma warning disable CS1591
        Type,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
