// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListMartechReports2FieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_at")]
        #pragma warning disable CS1591
        StartAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_at")]
        #pragma warning disable CS1591
        EndAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign_id")]
        #pragma warning disable CS1591
        CampaignId,
        #pragma warning restore CS1591
        [EnumMember(Value = "list_id")]
        #pragma warning disable CS1591
        ListId,
        #pragma warning restore CS1591
        [EnumMember(Value = "emails_sent")]
        #pragma warning disable CS1591
        EmailsSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "abuse_reports")]
        #pragma warning disable CS1591
        AbuseReports,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribed")]
        #pragma warning disable CS1591
        Unsubscribed,
        #pragma warning restore CS1591
        [EnumMember(Value = "sent_at")]
        #pragma warning disable CS1591
        SentAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "hard_bounces")]
        #pragma warning disable CS1591
        HardBounces,
        #pragma warning restore CS1591
        [EnumMember(Value = "soft_bounces")]
        #pragma warning disable CS1591
        SoftBounces,
        #pragma warning restore CS1591
        [EnumMember(Value = "syntax_errors")]
        #pragma warning disable CS1591
        SyntaxErrors,
        #pragma warning restore CS1591
        [EnumMember(Value = "forwards_count")]
        #pragma warning disable CS1591
        ForwardsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "forwards_opens")]
        #pragma warning disable CS1591
        ForwardsOpens,
        #pragma warning restore CS1591
        [EnumMember(Value = "opens_total")]
        #pragma warning disable CS1591
        OpensTotal,
        #pragma warning restore CS1591
        [EnumMember(Value = "unique_opens")]
        #pragma warning disable CS1591
        UniqueOpens,
        #pragma warning restore CS1591
        [EnumMember(Value = "open_rate")]
        #pragma warning disable CS1591
        OpenRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_open_at")]
        #pragma warning disable CS1591
        LastOpenAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "clicks_total")]
        #pragma warning disable CS1591
        ClicksTotal,
        #pragma warning restore CS1591
        [EnumMember(Value = "unique_clicks")]
        #pragma warning disable CS1591
        UniqueClicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "unique_subscriber_clicks")]
        #pragma warning disable CS1591
        UniqueSubscriberClicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "click_rate")]
        #pragma warning disable CS1591
        ClickRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_click_at")]
        #pragma warning disable CS1591
        LastClickAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "links")]
        #pragma warning disable CS1591
        Links,
        #pragma warning restore CS1591
        [EnumMember(Value = "human_opens_total")]
        #pragma warning disable CS1591
        HumanOpensTotal,
        #pragma warning restore CS1591
        [EnumMember(Value = "human_unique_opens")]
        #pragma warning disable CS1591
        HumanUniqueOpens,
        #pragma warning restore CS1591
        [EnumMember(Value = "human_open_rate")]
        #pragma warning disable CS1591
        HumanOpenRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
