// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListClubsEventsFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "group_id")]
        #pragma warning disable CS1591
        GroupId,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "type")]
        #pragma warning disable CS1591
        Type,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_at")]
        #pragma warning disable CS1591
        StartAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_at")]
        #pragma warning disable CS1591
        EndAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "timezone")]
        #pragma warning disable CS1591
        Timezone,
        #pragma warning restore CS1591
        [EnumMember(Value = "duration_minutes")]
        #pragma warning disable CS1591
        DurationMinutes,
        #pragma warning restore CS1591
        [EnumMember(Value = "location_id")]
        #pragma warning disable CS1591
        LocationId,
        #pragma warning restore CS1591
        [EnumMember(Value = "location_name")]
        #pragma warning disable CS1591
        LocationName,
        #pragma warning restore CS1591
        [EnumMember(Value = "opponent_id")]
        #pragma warning disable CS1591
        OpponentId,
        #pragma warning restore CS1591
        [EnumMember(Value = "opponent_name")]
        #pragma warning disable CS1591
        OpponentName,
        #pragma warning restore CS1591
        [EnumMember(Value = "home_team_name")]
        #pragma warning disable CS1591
        HomeTeamName,
        #pragma warning restore CS1591
        [EnumMember(Value = "away_team_name")]
        #pragma warning disable CS1591
        AwayTeamName,
        #pragma warning restore CS1591
        [EnumMember(Value = "home_score")]
        #pragma warning disable CS1591
        HomeScore,
        #pragma warning restore CS1591
        [EnumMember(Value = "away_score")]
        #pragma warning disable CS1591
        AwayScore,
        #pragma warning restore CS1591
        [EnumMember(Value = "score_for")]
        #pragma warning disable CS1591
        ScoreFor,
        #pragma warning restore CS1591
        [EnumMember(Value = "score_against")]
        #pragma warning disable CS1591
        ScoreAgainst,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_home")]
        #pragma warning disable CS1591
        IsHome,
        #pragma warning restore CS1591
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
