// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListAccountingBalancesheetsFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_at")]
        #pragma warning disable CS1591
        StartAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_at")]
        #pragma warning disable CS1591
        EndAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "net_assets_amount")]
        #pragma warning disable CS1591
        NetAssetsAmount,
        #pragma warning restore CS1591
        [EnumMember(Value = "assets")]
        #pragma warning disable CS1591
        Assets,
        #pragma warning restore CS1591
        [EnumMember(Value = "liabilities")]
        #pragma warning disable CS1591
        Liabilities,
        #pragma warning restore CS1591
        [EnumMember(Value = "equity")]
        #pragma warning disable CS1591
        Equity,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
