// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListCommerceAvailabilitiesFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "location_id")]
        #pragma warning disable CS1591
        LocationId,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_at")]
        #pragma warning disable CS1591
        StartAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_at")]
        #pragma warning disable CS1591
        EndAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "size")]
        #pragma warning disable CS1591
        Size,
        #pragma warning restore CS1591
        [EnumMember(Value = "item_id")]
        #pragma warning disable CS1591
        ItemId,
        #pragma warning restore CS1591
        [EnumMember(Value = "staff_user_id")]
        #pragma warning disable CS1591
        StaffUserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
