// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MarketingCampaign : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The from_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromEmail { get; set; }
#nullable restore
#else
        public string FromEmail { get; set; }
#endif
        /// <summary>The from_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromName { get; set; }
#nullable restore
#else
        public string FromName { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Associated listaudience IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ListIds { get; set; }
#nullable restore
#else
        public List<string> ListIds { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The preview_text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewText { get; set; }
#nullable restore
#else
        public string PreviewText { get; set; }
#endif
        /// <summary>The raw property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaignRawProperty? Raw { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaignRawProperty Raw { get; set; }
#endif
        /// <summary>The reply_to_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplyToEmail { get; set; }
#nullable restore
#else
        public string ReplyToEmail { get; set; }
#endif
        /// <summary>The send_at property</summary>
        public DateTimeOffset? SendAt { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaignStatus? Status { get; set; }
        /// <summary>The subject_line property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectLine { get; set; }
#nullable restore
#else
        public string SubjectLine { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaign"/> and sets the default values.
        /// </summary>
        public MarketingCampaign()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaign"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaign CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaign();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "from_email", n => { FromEmail = n.GetStringValue(); } },
                { "from_name", n => { FromName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "list_ids", n => { ListIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "preview_text", n => { PreviewText = n.GetStringValue(); } },
                { "raw", n => { Raw = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaignRawProperty>(global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaignRawProperty.CreateFromDiscriminatorValue); } },
                { "reply_to_email", n => { ReplyToEmail = n.GetStringValue(); } },
                { "send_at", n => { SendAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaignStatus>(); } },
                { "subject_line", n => { SubjectLine = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("from_email", FromEmail);
            writer.WriteStringValue("from_name", FromName);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfPrimitiveValues<string>("list_ids", ListIds);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("preview_text", PreviewText);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaignRawProperty>("raw", Raw);
            writer.WriteStringValue("reply_to_email", ReplyToEmail);
            writer.WriteDateTimeOffsetValue("send_at", SendAt);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.MarketingCampaignStatus>("status", Status);
            writer.WriteStringValue("subject_line", SubjectLine);
            writer.WriteStringValue("type", Type);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
