// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PatchAtsCompanyFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "address")]
        #pragma warning disable CS1591
        Address,
        #pragma warning restore CS1591
        [EnumMember(Value = "website_url")]
        #pragma warning disable CS1591
        WebsiteUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone")]
        #pragma warning disable CS1591
        Phone,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent_id")]
        #pragma warning disable CS1591
        ParentId,
        #pragma warning restore CS1591
        [EnumMember(Value = "recruiter_ids")]
        #pragma warning disable CS1591
        RecruiterIds,
        #pragma warning restore CS1591
        [EnumMember(Value = "metadata")]
        #pragma warning disable CS1591
        Metadata,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
