// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PatchMessagingMessageFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "channel_id")]
        #pragma warning disable CS1591
        ChannelId,
        #pragma warning restore CS1591
        [EnumMember(Value = "channel_ids")]
        #pragma warning disable CS1591
        ChannelIds,
        #pragma warning restore CS1591
        [EnumMember(Value = "channels")]
        #pragma warning disable CS1591
        Channels,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent_id")]
        #pragma warning disable CS1591
        ParentId,
        #pragma warning restore CS1591
        [EnumMember(Value = "root_message_id")]
        #pragma warning disable CS1591
        RootMessageId,
        #pragma warning restore CS1591
        [EnumMember(Value = "message_thread_identifier")]
        #pragma warning disable CS1591
        MessageThreadIdentifier,
        #pragma warning restore CS1591
        [EnumMember(Value = "author_member")]
        #pragma warning disable CS1591
        AuthorMember,
        #pragma warning restore CS1591
        [EnumMember(Value = "destination_members")]
        #pragma warning disable CS1591
        DestinationMembers,
        #pragma warning restore CS1591
        [EnumMember(Value = "hidden_members")]
        #pragma warning disable CS1591
        HiddenMembers,
        #pragma warning restore CS1591
        [EnumMember(Value = "mentioned_members")]
        #pragma warning disable CS1591
        MentionedMembers,
        #pragma warning restore CS1591
        [EnumMember(Value = "reactions")]
        #pragma warning disable CS1591
        Reactions,
        #pragma warning restore CS1591
        [EnumMember(Value = "subject")]
        #pragma warning disable CS1591
        Subject,
        #pragma warning restore CS1591
        [EnumMember(Value = "message")]
        #pragma warning disable CS1591
        Message,
        #pragma warning restore CS1591
        [EnumMember(Value = "message_html")]
        #pragma warning disable CS1591
        MessageHtml,
        #pragma warning restore CS1591
        [EnumMember(Value = "message_markdown")]
        #pragma warning disable CS1591
        MessageMarkdown,
        #pragma warning restore CS1591
        [EnumMember(Value = "attachments")]
        #pragma warning disable CS1591
        Attachments,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_url")]
        #pragma warning disable CS1591
        WebUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "reference")]
        #pragma warning disable CS1591
        Reference,
        #pragma warning restore CS1591
        [EnumMember(Value = "has_children")]
        #pragma warning disable CS1591
        HasChildren,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_unread")]
        #pragma warning disable CS1591
        IsUnread,
        #pragma warning restore CS1591
        [EnumMember(Value = "buttons")]
        #pragma warning disable CS1591
        Buttons,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
