// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    /// <summary>Why the refund was issued</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentRefundReason
    {
        [EnumMember(Value = "DUPLICATE")]
        #pragma warning disable CS1591
        Duplicate,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUDULENT")]
        #pragma warning disable CS1591
        Fraudulent,
        #pragma warning restore CS1591
        [EnumMember(Value = "REQUESTED_BY_CUSTOMER")]
        #pragma warning disable CS1591
        RequestedByCustomer,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
