// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PerformanceFeedbackType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PRAISE")]
        #pragma warning disable CS1591
        Praise,
        #pragma warning restore CS1591
        [EnumMember(Value = "FEEDBACK")]
        #pragma warning disable CS1591
        Feedback,
        #pragma warning restore CS1591
        [EnumMember(Value = "REQUESTED")]
        #pragma warning disable CS1591
        Requested,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
