// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PropertyAdsGroupTargetingGeographic : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.CityTarget>? Cities { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.CityTarget> Cities { get; set; }
#endif
        /// <summary>The countries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>? Countries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef> Countries { get; set; }
#endif
        /// <summary>The excluded_cities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.CityTarget>? ExcludedCities { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.CityTarget> ExcludedCities { get; set; }
#endif
        /// <summary>The excluded_countries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>? ExcludedCountries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef> ExcludedCountries { get; set; }
#endif
        /// <summary>The excluded_postal_codes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>? ExcludedPostalCodes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef> ExcludedPostalCodes { get; set; }
#endif
        /// <summary>The excluded_regions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>? ExcludedRegions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef> ExcludedRegions { get; set; }
#endif
        /// <summary>The excluded_us_dmas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>? ExcludedUsDmas { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef> ExcludedUsDmas { get; set; }
#endif
        /// <summary>The location_types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographicLocationTypesItem?>? LocationTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographicLocationTypesItem?> LocationTypes { get; set; }
#endif
        /// <summary>The postal_codes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>? PostalCodes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef> PostalCodes { get; set; }
#endif
        /// <summary>The presence_type property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographicPresenceType? PresenceType { get; set; }
        /// <summary>The regions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>? Regions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef> Regions { get; set; }
#endif
        /// <summary>The us_dmas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>? UsDmas { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.TargetRef> UsDmas { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographic"/> and sets the default values.
        /// </summary>
        public PropertyAdsGroupTargetingGeographic()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographic();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cities", n => { Cities = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.CityTarget>(global::Soenneker.Unified.OpenApiClient.Models.CityTarget.CreateFromDiscriminatorValue)?.AsList(); } },
                { "countries", n => { Countries = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>(global::Soenneker.Unified.OpenApiClient.Models.TargetRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "excluded_cities", n => { ExcludedCities = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.CityTarget>(global::Soenneker.Unified.OpenApiClient.Models.CityTarget.CreateFromDiscriminatorValue)?.AsList(); } },
                { "excluded_countries", n => { ExcludedCountries = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>(global::Soenneker.Unified.OpenApiClient.Models.TargetRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "excluded_postal_codes", n => { ExcludedPostalCodes = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>(global::Soenneker.Unified.OpenApiClient.Models.TargetRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "excluded_regions", n => { ExcludedRegions = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>(global::Soenneker.Unified.OpenApiClient.Models.TargetRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "excluded_us_dmas", n => { ExcludedUsDmas = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>(global::Soenneker.Unified.OpenApiClient.Models.TargetRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "location_types", n => { LocationTypes = n.GetCollectionOfEnumValues<global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographicLocationTypesItem>()?.AsList(); } },
                { "postal_codes", n => { PostalCodes = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>(global::Soenneker.Unified.OpenApiClient.Models.TargetRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "presence_type", n => { PresenceType = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographicPresenceType>(); } },
                { "regions", n => { Regions = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>(global::Soenneker.Unified.OpenApiClient.Models.TargetRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "us_dmas", n => { UsDmas = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>(global::Soenneker.Unified.OpenApiClient.Models.TargetRef.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.CityTarget>("cities", Cities);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>("countries", Countries);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.CityTarget>("excluded_cities", ExcludedCities);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>("excluded_countries", ExcludedCountries);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>("excluded_postal_codes", ExcludedPostalCodes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>("excluded_regions", ExcludedRegions);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>("excluded_us_dmas", ExcludedUsDmas);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographicLocationTypesItem>("location_types", LocationTypes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>("postal_codes", PostalCodes);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.PropertyAdsGroupTargetingGeographicPresenceType>("presence_type", PresenceType);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>("regions", Regions);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.TargetRef>("us_dmas", UsDmas);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
