// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertyCalendarEventOrganizerStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ACCEPTED")]
        #pragma warning disable CS1591
        Accepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        Rejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "TENTATIVE")]
        #pragma warning disable CS1591
        Tentative,
        #pragma warning restore CS1591
    }
}
