// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertyScimUserSchemasItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "urn:ietf:params:scim:schemas:core:2.0:User")]
        #pragma warning disable CS1591
        UrnColonIetfColonParamsColonScimColonSchemasColonCoreColon20ColonUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User")]
        #pragma warning disable CS1591
        UrnColonIetfColonParamsColonScimColonSchemasColonExtensionColonEnterpriseColon20ColonUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "urn:ietf:params:scim:schemas:extension:lattice:attributes:1.0:User")]
        #pragma warning disable CS1591
        UrnColonIetfColonParamsColonScimColonSchemasColonExtensionColonLatticeColonAttributesColon10ColonUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "urn:ietf:params:scim:schemas:extension:peakon:2.0:User")]
        #pragma warning disable CS1591
        UrnColonIetfColonParamsColonScimColonSchemasColonExtensionColonPeakonColon20ColonUser,
        #pragma warning restore CS1591
    }
}
