// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertyAdsReportMetricsAdStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "UNSPECIFIED")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAUSED")]
        #pragma warning disable CS1591
        Paused,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARCHIVED")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSING")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSING_FAILED")]
        #pragma warning disable CS1591
        ProcessingFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "DRAFT")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULED_FOR_DELETION")]
        #pragma warning disable CS1591
        ScheduledForDeletion,
        #pragma warning restore CS1591
    }
}
