// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Property_AdsReportMetrics_campaign : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The advertising_channel_type property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_advertising_channel_type? AdvertisingChannelType { get; set; }
        /// <summary>The budget_amount property</summary>
        public double? BudgetAmount { get; set; }
        /// <summary>The budget_period property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_budget_period? BudgetPeriod { get; set; }
        /// <summary>The campaign_budget_identifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignBudgetIdentifier { get; set; }
#nullable restore
#else
        public string CampaignBudgetIdentifier { get; set; }
#endif
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The end_at property</summary>
        public DateTimeOffset? EndAt { get; set; }
        /// <summary>The frequency_cap property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_frequency_cap? FrequencyCap { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_frequency_cap FrequencyCap { get; set; }
#endif
        /// <summary>The goal property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_goal? Goal { get; set; }
        /// <summary>The has_eu_political_ads property</summary>
        public bool? HasEuPoliticalAds { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The planned_spend_amount property</summary>
        public double? PlannedSpendAmount { get; set; }
        /// <summary>The raw property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_raw? Raw { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_raw Raw { get; set; }
#endif
        /// <summary>The start_at property</summary>
        public DateTimeOffset? StartAt { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_status? Status { get; set; }
        /// <summary>The targeting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_targeting? Targeting { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_targeting Targeting { get; set; }
#endif
        /// <summary>The total_spend_amount property</summary>
        public double? TotalSpendAmount { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign"/> and sets the default values.
        /// </summary>
        public Property_AdsReportMetrics_campaign()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "advertising_channel_type", n => { AdvertisingChannelType = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_advertising_channel_type>(); } },
                { "budget_amount", n => { BudgetAmount = n.GetDoubleValue(); } },
                { "budget_period", n => { BudgetPeriod = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_budget_period>(); } },
                { "campaign_budget_identifier", n => { CampaignBudgetIdentifier = n.GetStringValue(); } },
                { "category", n => { Category = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "end_at", n => { EndAt = n.GetDateTimeOffsetValue(); } },
                { "frequency_cap", n => { FrequencyCap = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_frequency_cap>(global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_frequency_cap.CreateFromDiscriminatorValue); } },
                { "goal", n => { Goal = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_goal>(); } },
                { "has_eu_political_ads", n => { HasEuPoliticalAds = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "planned_spend_amount", n => { PlannedSpendAmount = n.GetDoubleValue(); } },
                { "raw", n => { Raw = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_raw>(global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_raw.CreateFromDiscriminatorValue); } },
                { "start_at", n => { StartAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_status>(); } },
                { "targeting", n => { Targeting = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_targeting>(global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_targeting.CreateFromDiscriminatorValue); } },
                { "total_spend_amount", n => { TotalSpendAmount = n.GetDoubleValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_advertising_channel_type>("advertising_channel_type", AdvertisingChannelType);
            writer.WriteDoubleValue("budget_amount", BudgetAmount);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_budget_period>("budget_period", BudgetPeriod);
            writer.WriteStringValue("campaign_budget_identifier", CampaignBudgetIdentifier);
            writer.WriteStringValue("category", Category);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("currency", Currency);
            writer.WriteDateTimeOffsetValue("end_at", EndAt);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_frequency_cap>("frequency_cap", FrequencyCap);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_goal>("goal", Goal);
            writer.WriteBoolValue("has_eu_political_ads", HasEuPoliticalAds);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteDoubleValue("planned_spend_amount", PlannedSpendAmount);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_raw>("raw", Raw);
            writer.WriteDateTimeOffsetValue("start_at", StartAt);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.Property_AdsReportMetrics_campaign_targeting>("targeting", Targeting);
            writer.WriteDoubleValue("total_spend_amount", TotalSpendAmount);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
