// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertyCrmEventTask_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        COMPLETED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_STARTED")]
        #pragma warning disable CS1591
        NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORK_IN_PROGRESS")]
        #pragma warning disable CS1591
        WORK_IN_PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEFERRED")]
        #pragma warning disable CS1591
        DEFERRED,
        #pragma warning restore CS1591
    }
}
