// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertyScimUserUrnIetfParamsScimSchemasExtensionLatticeAttributes10User_ethnicity
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Caucasian")]
        #pragma warning disable CS1591
        Caucasian,
        #pragma warning restore CS1591
        [EnumMember(Value = "East Asian")]
        #pragma warning disable CS1591
        EastAsian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Middle Eastern")]
        #pragma warning disable CS1591
        MiddleEastern,
        #pragma warning restore CS1591
        [EnumMember(Value = "Black")]
        #pragma warning disable CS1591
        Black,
        #pragma warning restore CS1591
        [EnumMember(Value = "Biracial (South Asian & Caucasian)")]
        #pragma warning disable CS1591
        BiracialSouthAsianCaucasian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Filipino")]
        #pragma warning disable CS1591
        Filipino,
        #pragma warning restore CS1591
        [EnumMember(Value = "South Asian")]
        #pragma warning disable CS1591
        SouthAsian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Indian")]
        #pragma warning disable CS1591
        Indian,
        #pragma warning restore CS1591
        [EnumMember(Value = "White")]
        #pragma warning disable CS1591
        White,
        #pragma warning restore CS1591
        [EnumMember(Value = "Asian")]
        #pragma warning disable CS1591
        Asian,
        #pragma warning restore CS1591
    }
}
