// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertyShippingShipmentInsuranceCoverageType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "STANDARD")]
        #pragma warning disable CS1591
        Standard,
        #pragma warning restore CS1591
        [EnumMember(Value = "PREMIUM")]
        #pragma warning disable CS1591
        Premium,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
