// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertyAdsGroupTargetingOptimization_mode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TARGETING")]
        #pragma warning disable CS1591
        TARGETING,
        #pragma warning restore CS1591
        [EnumMember(Value = "OBSERVATION")]
        #pragma warning disable CS1591
        OBSERVATION,
        #pragma warning restore CS1591
    }
}
