// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    /// <summary>
    /// An authentication object that represents a specific authorized user&apos;s connection to an integration.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PropertyConnectionAuth : IAdditionalDataHolder, IParsable
    {
        /// <summary>The access_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The api_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiUrl { get; set; }
#nullable restore
#else
        public string ApiUrl { get; set; }
#endif
        /// <summary>The app_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppId { get; set; }
#nullable restore
#else
        public string AppId { get; set; }
#endif
        /// <summary>The audience property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Audience { get; set; }
#nullable restore
#else
        public string Audience { get; set; }
#endif
        /// <summary>The authorize_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizeUrl { get; set; }
#nullable restore
#else
        public string AuthorizeUrl { get; set; }
#endif
        /// <summary>The client_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The client_secret property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientSecret { get; set; }
#nullable restore
#else
        public string ClientSecret { get; set; }
#endif
        /// <summary>The consumer_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConsumerKey { get; set; }
#nullable restore
#else
        public string ConsumerKey { get; set; }
#endif
        /// <summary>The consumer_secret property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConsumerSecret { get; set; }
#nullable restore
#else
        public string ConsumerSecret { get; set; }
#endif
        /// <summary>The dev_api_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DevApiKey { get; set; }
#nullable restore
#else
        public string DevApiKey { get; set; }
#endif
        /// <summary>The emails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Emails { get; set; }
#nullable restore
#else
        public List<string> Emails { get; set; }
#endif
        /// <summary>The expires_in property</summary>
        public double? ExpiresIn { get; set; }
        /// <summary>The expiry_date property</summary>
        public DateTimeOffset? ExpiryDate { get; set; }
        /// <summary>The key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.PropertyConnectionAuthMetaProperty? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.PropertyConnectionAuthMetaProperty Meta { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>When integration.auth_type = &quot;other&quot;, this field contains the authentication credentials in the same order as token_names</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? OtherAuthInfo { get; set; }
#nullable restore
#else
        public List<string> OtherAuthInfo { get; set; }
#endif
        /// <summary>The pem property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pem { get; set; }
#nullable restore
#else
        public string Pem { get; set; }
#endif
        /// <summary>The refresh_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefreshToken { get; set; }
#nullable restore
#else
        public string RefreshToken { get; set; }
#endif
        /// <summary>The refresh_token_expires_date property</summary>
        public DateTimeOffset? RefreshTokenExpiresDate { get; set; }
        /// <summary>The refresh_token_expires_in property</summary>
        public double? RefreshTokenExpiresIn { get; set; }
        /// <summary>The refresh_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefreshUrl { get; set; }
#nullable restore
#else
        public string RefreshUrl { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>The token_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenUrl { get; set; }
#nullable restore
#else
        public string TokenUrl { get; set; }
#endif
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Models.PropertyConnectionAuth"/> and sets the default values.
        /// </summary>
        public PropertyConnectionAuth()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.PropertyConnectionAuth"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.PropertyConnectionAuth CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Unified.OpenApiClient.Models.PropertyConnectionAuth();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_token", n => { AccessToken = n.GetStringValue(); } },
                { "api_url", n => { ApiUrl = n.GetStringValue(); } },
                { "app_id", n => { AppId = n.GetStringValue(); } },
                { "audience", n => { Audience = n.GetStringValue(); } },
                { "authorize_url", n => { AuthorizeUrl = n.GetStringValue(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "client_secret", n => { ClientSecret = n.GetStringValue(); } },
                { "consumer_key", n => { ConsumerKey = n.GetStringValue(); } },
                { "consumer_secret", n => { ConsumerSecret = n.GetStringValue(); } },
                { "dev_api_key", n => { DevApiKey = n.GetStringValue(); } },
                { "emails", n => { Emails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "expires_in", n => { ExpiresIn = n.GetDoubleValue(); } },
                { "expiry_date", n => { ExpiryDate = n.GetDateTimeOffsetValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.PropertyConnectionAuthMetaProperty>(global::Soenneker.Unified.OpenApiClient.Models.PropertyConnectionAuthMetaProperty.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "other_auth_info", n => { OtherAuthInfo = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "pem", n => { Pem = n.GetStringValue(); } },
                { "refresh_token", n => { RefreshToken = n.GetStringValue(); } },
                { "refresh_token_expires_date", n => { RefreshTokenExpiresDate = n.GetDateTimeOffsetValue(); } },
                { "refresh_token_expires_in", n => { RefreshTokenExpiresIn = n.GetDoubleValue(); } },
                { "refresh_url", n => { RefreshUrl = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "token_url", n => { TokenUrl = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_token", AccessToken);
            writer.WriteStringValue("api_url", ApiUrl);
            writer.WriteStringValue("app_id", AppId);
            writer.WriteStringValue("audience", Audience);
            writer.WriteStringValue("authorize_url", AuthorizeUrl);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteStringValue("client_secret", ClientSecret);
            writer.WriteStringValue("consumer_key", ConsumerKey);
            writer.WriteStringValue("consumer_secret", ConsumerSecret);
            writer.WriteStringValue("dev_api_key", DevApiKey);
            writer.WriteCollectionOfPrimitiveValues<string>("emails", Emails);
            writer.WriteDoubleValue("expires_in", ExpiresIn);
            writer.WriteDateTimeOffsetValue("expiry_date", ExpiryDate);
            writer.WriteStringValue("key", Key);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.PropertyConnectionAuthMetaProperty>("meta", Meta);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("other_auth_info", OtherAuthInfo);
            writer.WriteStringValue("pem", Pem);
            writer.WriteStringValue("refresh_token", RefreshToken);
            writer.WriteDateTimeOffsetValue("refresh_token_expires_date", RefreshTokenExpiresDate);
            writer.WriteDoubleValue("refresh_token_expires_in", RefreshTokenExpiresIn);
            writer.WriteStringValue("refresh_url", RefreshUrl);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("token", Token);
            writer.WriteStringValue("token_url", TokenUrl);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
