// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SigningSignatory_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "SENT")]
        #pragma warning disable CS1591
        SENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELIVERED")]
        #pragma warning disable CS1591
        DELIVERED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGNED")]
        #pragma warning disable CS1591
        SIGNED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECLINED")]
        #pragma warning disable CS1591
        DECLINED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
    }
}
