// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SigningSignatory_role
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SIGNER")]
        #pragma warning disable CS1591
        SIGNER,
        #pragma warning restore CS1591
        [EnumMember(Value = "CC")]
        #pragma warning disable CS1591
        CC,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVER")]
        #pragma warning disable CS1591
        APPROVER,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PERSON_SIGNER")]
        #pragma warning disable CS1591
        IN_PERSON_SIGNER,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIEWER")]
        #pragma warning disable CS1591
        VIEWER,
        #pragma warning restore CS1591
    }
}
