// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StorageFileType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FILE")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
        [EnumMember(Value = "FOLDER")]
        #pragma warning disable CS1591
        Folder,
        #pragma warning restore CS1591
    }
}
