// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TicketingTicket_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        ACTIVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOSED")]
        #pragma warning disable CS1591
        CLOSED,
        #pragma warning restore CS1591
    }
}
