// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UcCall : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The contacts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.UcContact>? Contacts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.UcContact> Contacts { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The end_at property</summary>
        public DateTimeOffset? EndAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_private property</summary>
        public bool? IsPrivate { get; set; }
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Unified.OpenApiClient.Models.UcMetadata>? Metadata { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Unified.OpenApiClient.Models.UcMetadata> Metadata { get; set; }
#endif
        /// <summary>The raw property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.UcCallRawProperty? Raw { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.UcCallRawProperty Raw { get; set; }
#endif
        /// <summary>The start_at property</summary>
        public DateTimeOffset? StartAt { get; set; }
        /// <summary>The telephone number called</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Unified.OpenApiClient.Models.PropertyUcCallTelephone? Telephone { get; set; }
#nullable restore
#else
        public global::Soenneker.Unified.OpenApiClient.Models.PropertyUcCallTelephone Telephone { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Unified.OpenApiClient.Models.UcCallType? Type { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>The user_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>The user_phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserPhone { get; set; }
#nullable restore
#else
        public string UserPhone { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Models.UcCall"/> and sets the default values.
        /// </summary>
        public UcCall()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.UcCall"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Unified.OpenApiClient.Models.UcCall CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Unified.OpenApiClient.Models.UcCall();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "contacts", n => { Contacts = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.UcContact>(global::Soenneker.Unified.OpenApiClient.Models.UcContact.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "end_at", n => { EndAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_private", n => { IsPrivate = n.GetBoolValue(); } },
                { "metadata", n => { Metadata = n.GetCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.UcMetadata>(global::Soenneker.Unified.OpenApiClient.Models.UcMetadata.CreateFromDiscriminatorValue)?.AsList(); } },
                { "raw", n => { Raw = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.UcCallRawProperty>(global::Soenneker.Unified.OpenApiClient.Models.UcCallRawProperty.CreateFromDiscriminatorValue); } },
                { "start_at", n => { StartAt = n.GetDateTimeOffsetValue(); } },
                { "telephone", n => { Telephone = n.GetObjectValue<global::Soenneker.Unified.OpenApiClient.Models.PropertyUcCallTelephone>(global::Soenneker.Unified.OpenApiClient.Models.PropertyUcCallTelephone.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Unified.OpenApiClient.Models.UcCallType>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "user_name", n => { UserName = n.GetStringValue(); } },
                { "user_phone", n => { UserPhone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.UcContact>("contacts", Contacts);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteDateTimeOffsetValue("end_at", EndAt);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_private", IsPrivate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Unified.OpenApiClient.Models.UcMetadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.UcCallRawProperty>("raw", Raw);
            writer.WriteDateTimeOffsetValue("start_at", StartAt);
            writer.WriteObjectValue<global::Soenneker.Unified.OpenApiClient.Models.PropertyUcCallTelephone>("telephone", Telephone);
            writer.WriteEnumValue<global::Soenneker.Unified.OpenApiClient.Models.UcCallType>("type", Type);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteStringValue("user_name", UserName);
            writer.WriteStringValue("user_phone", UserPhone);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
