// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateAssessmentOrderFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "workspace_id")]
        #pragma warning disable CS1591
        WorkspaceId,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection_id")]
        #pragma warning disable CS1591
        ConnectionId,
        #pragma warning restore CS1591
        [EnumMember(Value = "webhook_id")]
        #pragma warning disable CS1591
        WebhookId,
        #pragma warning restore CS1591
        [EnumMember(Value = "package_id")]
        #pragma warning disable CS1591
        PackageId,
        #pragma warning restore CS1591
        [EnumMember(Value = "parameters")]
        #pragma warning disable CS1591
        Parameters,
        #pragma warning restore CS1591
        [EnumMember(Value = "target_url")]
        #pragma warning disable CS1591
        TargetUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "reference")]
        #pragma warning disable CS1591
        Reference,
        #pragma warning restore CS1591
        [EnumMember(Value = "application_id")]
        #pragma warning disable CS1591
        ApplicationId,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_id")]
        #pragma warning disable CS1591
        JobId,
        #pragma warning restore CS1591
        [EnumMember(Value = "company_id")]
        #pragma warning disable CS1591
        CompanyId,
        #pragma warning restore CS1591
        [EnumMember(Value = "candidate_id")]
        #pragma warning disable CS1591
        CandidateId,
        #pragma warning restore CS1591
        [EnumMember(Value = "employee_id")]
        #pragma warning disable CS1591
        EmployeeId,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_name")]
        #pragma warning disable CS1591
        ProfileName,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_first_name")]
        #pragma warning disable CS1591
        ProfileFirstName,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_last_name")]
        #pragma warning disable CS1591
        ProfileLastName,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_resume_url")]
        #pragma warning disable CS1591
        ProfileResumeUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_ip_address")]
        #pragma warning disable CS1591
        ProfileIpAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_date_of_birth")]
        #pragma warning disable CS1591
        ProfileDateOfBirth,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_addresses")]
        #pragma warning disable CS1591
        ProfileAddresses,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_gender")]
        #pragma warning disable CS1591
        ProfileGender,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_emails")]
        #pragma warning disable CS1591
        ProfileEmails,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_telephones")]
        #pragma warning disable CS1591
        ProfileTelephones,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_national_identifier")]
        #pragma warning disable CS1591
        ProfileNationalIdentifier,
        #pragma warning restore CS1591
        [EnumMember(Value = "profile_social_media_urls")]
        #pragma warning disable CS1591
        ProfileSocialMediaUrls,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_completed_at")]
        #pragma warning disable CS1591
        ResponseCompletedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_expires_at")]
        #pragma warning disable CS1591
        ResponseExpiresAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_issued_at")]
        #pragma warning disable CS1591
        ResponseIssuedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_status")]
        #pragma warning disable CS1591
        ResponseStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_score")]
        #pragma warning disable CS1591
        ResponseScore,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_max_score")]
        #pragma warning disable CS1591
        ResponseMaxScore,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_url")]
        #pragma warning disable CS1591
        ResponseUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_redirect_url")]
        #pragma warning disable CS1591
        ResponseRedirectUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_download_urls")]
        #pragma warning disable CS1591
        ResponseDownloadUrls,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_details")]
        #pragma warning disable CS1591
        ResponseDetails,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_source")]
        #pragma warning disable CS1591
        ResponseSource,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_attributes")]
        #pragma warning disable CS1591
        ResponseAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
