// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateAccountingContact2FieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "first_name")]
        #pragma warning disable CS1591
        FirstName,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_name")]
        #pragma warning disable CS1591
        LastName,
        #pragma warning restore CS1591
        [EnumMember(Value = "emails")]
        #pragma warning disable CS1591
        Emails,
        #pragma warning restore CS1591
        [EnumMember(Value = "telephones")]
        #pragma warning disable CS1591
        Telephones,
        #pragma warning restore CS1591
        [EnumMember(Value = "currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing_address")]
        #pragma warning disable CS1591
        BillingAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_address")]
        #pragma warning disable CS1591
        ShippingAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_active")]
        #pragma warning disable CS1591
        IsActive,
        #pragma warning restore CS1591
        [EnumMember(Value = "tax_exemption")]
        #pragma warning disable CS1591
        TaxExemption,
        #pragma warning restore CS1591
        [EnumMember(Value = "tax_number")]
        #pragma warning disable CS1591
        TaxNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_customer")]
        #pragma warning disable CS1591
        IsCustomer,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_supplier")]
        #pragma warning disable CS1591
        IsSupplier,
        #pragma warning restore CS1591
        [EnumMember(Value = "portal_url")]
        #pragma warning disable CS1591
        PortalUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_methods")]
        #pragma warning disable CS1591
        PaymentMethods,
        #pragma warning restore CS1591
        [EnumMember(Value = "company_name")]
        #pragma warning disable CS1591
        CompanyName,
        #pragma warning restore CS1591
        [EnumMember(Value = "identification")]
        #pragma warning disable CS1591
        Identification,
        #pragma warning restore CS1591
        [EnumMember(Value = "associated_contacts")]
        #pragma warning disable CS1591
        AssociatedContacts,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_id")]
        #pragma warning disable CS1591
        OrganizationId,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
