// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VerificationPackage_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "IDENTITY_VERIFICATION")]
        #pragma warning disable CS1591
        IDENTITY_VERIFICATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCREENING")]
        #pragma warning disable CS1591
        SCREENING,
        #pragma warning restore CS1591
        [EnumMember(Value = "BACKGROUND_CHECK")]
        #pragma warning disable CS1591
        BACKGROUND_CHECK,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMPLOYMENT_VERIFICATION")]
        #pragma warning disable CS1591
        EMPLOYMENT_VERIFICATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "EDUCATION_VERIFICATION")]
        #pragma warning disable CS1591
        EDUCATION_VERIFICATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREDIT_CHECK")]
        #pragma warning disable CS1591
        CREDIT_CHECK,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_PREVENTION")]
        #pragma warning disable CS1591
        FRAUD_PREVENTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
    }
}
