// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Repo.Item.Pullrequest.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        Updated_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_ids")]
        #pragma warning disable CS1591
        User_ids,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_id")]
        #pragma warning disable CS1591
        Repo_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "labels")]
        #pragma warning disable CS1591
        Labels,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed_at")]
        #pragma warning disable CS1591
        Closed_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "commit_ids")]
        #pragma warning disable CS1591
        Commit_ids,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
