// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Repo.Item.Branch;
using Soenneker.Unified.OpenApiClient.Repo.Item.Commit;
using Soenneker.Unified.OpenApiClient.Repo.Item.Organization;
using Soenneker.Unified.OpenApiClient.Repo.Item.Pullrequest;
using Soenneker.Unified.OpenApiClient.Repo.Item.Repository;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Unified.OpenApiClient.Repo.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \repo\{connectionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithConnectionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The branch property</summary>
        public global::Soenneker.Unified.OpenApiClient.Repo.Item.Branch.BranchRequestBuilder Branch
        {
            get => new global::Soenneker.Unified.OpenApiClient.Repo.Item.Branch.BranchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The commit property</summary>
        public global::Soenneker.Unified.OpenApiClient.Repo.Item.Commit.CommitRequestBuilder Commit
        {
            get => new global::Soenneker.Unified.OpenApiClient.Repo.Item.Commit.CommitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organization property</summary>
        public global::Soenneker.Unified.OpenApiClient.Repo.Item.Organization.OrganizationRequestBuilder Organization
        {
            get => new global::Soenneker.Unified.OpenApiClient.Repo.Item.Organization.OrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pullrequest property</summary>
        public global::Soenneker.Unified.OpenApiClient.Repo.Item.Pullrequest.PullrequestRequestBuilder Pullrequest
        {
            get => new global::Soenneker.Unified.OpenApiClient.Repo.Item.Pullrequest.PullrequestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repository property</summary>
        public global::Soenneker.Unified.OpenApiClient.Repo.Item.Repository.RepositoryRequestBuilder Repository
        {
            get => new global::Soenneker.Unified.OpenApiClient.Repo.Item.Repository.RepositoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Repo.Item.WithConnectionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConnectionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repo/{connectionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Repo.Item.WithConnectionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConnectionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repo/{connectionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
