// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Datastore.Item.Database;
using Soenneker.Unified.OpenApiClient.Datastore.Item.Query;
using Soenneker.Unified.OpenApiClient.Datastore.Item.Record;
using Soenneker.Unified.OpenApiClient.Datastore.Item.Table;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Unified.OpenApiClient.Datastore.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \datastore\{connectionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithConnectionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The database property</summary>
        public global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.DatabaseRequestBuilder Database
        {
            get => new global::Soenneker.Unified.OpenApiClient.Datastore.Item.Database.DatabaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The query property</summary>
        public global::Soenneker.Unified.OpenApiClient.Datastore.Item.Query.QueryRequestBuilder Query
        {
            get => new global::Soenneker.Unified.OpenApiClient.Datastore.Item.Query.QueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The record property</summary>
        public global::Soenneker.Unified.OpenApiClient.Datastore.Item.Record.RecordRequestBuilder Record
        {
            get => new global::Soenneker.Unified.OpenApiClient.Datastore.Item.Record.RecordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The table property</summary>
        public global::Soenneker.Unified.OpenApiClient.Datastore.Item.Table.TableRequestBuilder Table
        {
            get => new global::Soenneker.Unified.OpenApiClient.Datastore.Item.Table.TableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Datastore.Item.WithConnectionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConnectionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/datastore/{connectionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Datastore.Item.WithConnectionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConnectionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/datastore/{connectionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
