// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Unified.Integration.Auth.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Unified.OpenApiClient.Unified.Integration.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \unified\integration\auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Unified.OpenApiClient.unified.integration.auth.item collection</summary>
        /// <param name="position">The ID of the workspace</param>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Unified.Integration.Auth.Item.WithWorkspaceItemRequestBuilder"/></returns>
        public global::Soenneker.Unified.OpenApiClient.Unified.Integration.Auth.Item.WithWorkspaceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("workspaceId", position);
                return new global::Soenneker.Unified.OpenApiClient.Unified.Integration.Auth.Item.WithWorkspaceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Unified.Integration.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/unified/integration/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Unified.Integration.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/unified/integration/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
