// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Models;
using Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project
{
    /// <summary>
    /// Builds and executes requests for operations under \task\{connectionId}\project
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Unified.OpenApiClient.task.item.project.item collection</summary>
        /// <param name="position">ID of the Project</param>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.Item.ProjectItemRequestBuilder"/></returns>
        public global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.Item.ProjectItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.Item.ProjectItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/task/{connectionId}/project{?company_id*,fields*,limit*,offset*,order*,parent_id*,query*,raw*,sort*,updated_gte*,user_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/task/{connectionId}/project{?company_id*,fields*,limit*,offset*,order*,parent_id*,query*,raw*,sort*,updated_gte*,user_id*}", rawUrl)
        {
        }
        /// <summary>
        /// List all projects
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Unified.OpenApiClient.Models.TaskProject&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Unified.OpenApiClient.Models.TaskProject>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder.ProjectRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Unified.OpenApiClient.Models.TaskProject>> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder.ProjectRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Unified.OpenApiClient.Models.TaskProject>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.TaskProject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Create a project
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.TaskProject"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.TaskProject?> PostAsync(global::Soenneker.Unified.OpenApiClient.Models.TaskProject body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder.ProjectRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.TaskProject> PostAsync(global::Soenneker.Unified.OpenApiClient.Models.TaskProject body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder.ProjectRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.TaskProject>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.TaskProject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all projects
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder.ProjectRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder.ProjectRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a project
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.TaskProject body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder.ProjectRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.TaskProject body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder.ProjectRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Unified.OpenApiClient.TaskNamespace.Item.Project.ProjectRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List all projects
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectRequestBuilderGetQueryParameters 
        {
            /// <summary>The company ID to filter by (reference to HrisCompany)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("company_id")]
            public string? CompanyId { get; set; }
#nullable restore
#else
            [QueryParameter("company_id")]
            public string CompanyId { get; set; }
#endif
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.ListTaskProjects2FieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.ListTaskProjects2FieldsParameterItem[] Fields { get; set; }
#endif
            [QueryParameter("limit")]
            public double? Limit { get; set; }
            [QueryParameter("offset")]
            public double? Offset { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>The parent ID to filter by</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parent_id")]
            public string? ParentId { get; set; }
#nullable restore
#else
            [QueryParameter("parent_id")]
            public string ParentId { get; set; }
#endif
            /// <summary>Query string to search. eg. email address or name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>&quot;Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            /// <summary>Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("updated_gte")]
            public string? UpdatedGte { get; set; }
#nullable restore
#else
            [QueryParameter("updated_gte")]
            public string UpdatedGte { get; set; }
#endif
            /// <summary>The user/employee ID to filter by (reference to HrisEmployee)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("user_id")]
            public string? UserId { get; set; }
#nullable restore
#else
            [QueryParameter("user_id")]
            public string UserId { get; set; }
#endif
        }
        /// <summary>
        /// Create a project
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectRequestBuilderPostQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.CreateTaskProject2FieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.CreateTaskProject2FieldsParameterItem[] Fields { get; set; }
#endif
            /// <summary>&quot;Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
