// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Messaging.Item.Message.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        Updated_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "channel_id")]
        #pragma warning disable CS1591
        Channel_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "channel_ids")]
        #pragma warning disable CS1591
        Channel_ids,
        #pragma warning restore CS1591
        [EnumMember(Value = "channels")]
        #pragma warning disable CS1591
        Channels,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent_id")]
        #pragma warning disable CS1591
        Parent_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "root_message_id")]
        #pragma warning disable CS1591
        Root_message_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "message_thread_identifier")]
        #pragma warning disable CS1591
        Message_thread_identifier,
        #pragma warning restore CS1591
        [EnumMember(Value = "author_member")]
        #pragma warning disable CS1591
        Author_member,
        #pragma warning restore CS1591
        [EnumMember(Value = "destination_members")]
        #pragma warning disable CS1591
        Destination_members,
        #pragma warning restore CS1591
        [EnumMember(Value = "hidden_members")]
        #pragma warning disable CS1591
        Hidden_members,
        #pragma warning restore CS1591
        [EnumMember(Value = "mentioned_members")]
        #pragma warning disable CS1591
        Mentioned_members,
        #pragma warning restore CS1591
        [EnumMember(Value = "reactions")]
        #pragma warning disable CS1591
        Reactions,
        #pragma warning restore CS1591
        [EnumMember(Value = "subject")]
        #pragma warning disable CS1591
        Subject,
        #pragma warning restore CS1591
        [EnumMember(Value = "message")]
        #pragma warning disable CS1591
        Message,
        #pragma warning restore CS1591
        [EnumMember(Value = "message_html")]
        #pragma warning disable CS1591
        Message_html,
        #pragma warning restore CS1591
        [EnumMember(Value = "message_markdown")]
        #pragma warning disable CS1591
        Message_markdown,
        #pragma warning restore CS1591
        [EnumMember(Value = "attachments")]
        #pragma warning disable CS1591
        Attachments,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_url")]
        #pragma warning disable CS1591
        Web_url,
        #pragma warning restore CS1591
        [EnumMember(Value = "reference")]
        #pragma warning disable CS1591
        Reference,
        #pragma warning restore CS1591
        [EnumMember(Value = "has_children")]
        #pragma warning disable CS1591
        Has_children,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_unread")]
        #pragma warning disable CS1591
        Is_unread,
        #pragma warning restore CS1591
        [EnumMember(Value = "buttons")]
        #pragma warning disable CS1591
        Buttons,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
