// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \ads\{connectionId}\campaign\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CampaignItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CampaignItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ads/{connectionId}/campaign/{id}{?fields*,raw*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CampaignItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ads/{connectionId}/campaign/{id}{?fields*,raw*}", rawUrl)
        {
        }
        /// <summary>
        /// Remove a campaign
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve a campaign
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign?> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a campaign
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign?> PatchAsync(global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign> PatchAsync(global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a campaign
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign?> PutAsync(global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign> PutAsync(global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Remove a campaign
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Retrieve a campaign
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a campaign
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Update a campaign
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.AdsCampaign body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder.CampaignItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Unified.OpenApiClient.Ads.Item.Campaign.Item.CampaignItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve a campaign
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CampaignItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.GetAdsCampaignFieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.GetAdsCampaignFieldsParameterItem[] Fields { get; set; }
#endif
            /// <summary>Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
        }
        /// <summary>
        /// Update a campaign
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CampaignItemRequestBuilderPatchQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.PatchAdsCampaignFieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.PatchAdsCampaignFieldsParameterItem[] Fields { get; set; }
#endif
            /// <summary>Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
        }
        /// <summary>
        /// Update a campaign
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CampaignItemRequestBuilderPutQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.UpdateAdsCampaignFieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.UpdateAdsCampaignFieldsParameterItem[] Fields { get; set; }
#endif
            /// <summary>Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
