// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.Item;
using Soenneker.Unified.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount
{
    /// <summary>
    /// Builds and executes requests for operations under \accounting\{connectionId}\bankfeedaccount
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BankfeedaccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Unified.OpenApiClient.accounting.item.bankfeedaccount.item collection</summary>
        /// <param name="position">ID of the Bankfeedaccount</param>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.Item.BankfeedaccountItemRequestBuilder"/></returns>
        public global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.Item.BankfeedaccountItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.Item.BankfeedaccountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BankfeedaccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounting/{connectionId}/bankfeedaccount{?fields*,limit*,offset*,order*,org_id*,query*,raw*,sort*,type*,updated_gte*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BankfeedaccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounting/{connectionId}/bankfeedaccount{?fields*,limit*,offset*,order*,org_id*,query*,raw*,sort*,type*,updated_gte*}", rawUrl)
        {
        }
        /// <summary>
        /// List all bankfeedaccounts
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder.BankfeedaccountRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount>> GetAsync(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder.BankfeedaccountRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Create a bankfeedaccount
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount?> PostAsync(global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder.BankfeedaccountRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount> PostAsync(global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder.BankfeedaccountRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount>(requestInfo, global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all bankfeedaccounts
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder.BankfeedaccountRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder.BankfeedaccountRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a bankfeedaccount
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder.BankfeedaccountRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Unified.OpenApiClient.Models.AccountingBankfeedaccount body, Action<RequestConfiguration<global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder.BankfeedaccountRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Unified.OpenApiClient.Accounting.Item.Bankfeedaccount.BankfeedaccountRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List all bankfeedaccounts
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BankfeedaccountRequestBuilderGetQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.ListAccountingBankfeedaccountsFieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.ListAccountingBankfeedaccountsFieldsParameterItem[] Fields { get; set; }
#endif
            [QueryParameter("limit")]
            public double? Limit { get; set; }
            [QueryParameter("offset")]
            public double? Offset { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>The org ID to filter by (reference to AccountingOrganization)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("org_id")]
            public string? OrgId { get; set; }
#nullable restore
#else
            [QueryParameter("org_id")]
            public string OrgId { get; set; }
#endif
            /// <summary>Query string to search. eg. email address or name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>&quot;Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public string? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public string Type { get; set; }
#endif
            /// <summary>Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("updated_gte")]
            public string? UpdatedGte { get; set; }
#nullable restore
#else
            [QueryParameter("updated_gte")]
            public string UpdatedGte { get; set; }
#endif
        }
        /// <summary>
        /// Create a bankfeedaccount
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BankfeedaccountRequestBuilderPostQueryParameters 
        {
            /// <summary>Fields to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.CreateAccountingBankfeedaccountFieldsParameterItem[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public global::Soenneker.Unified.OpenApiClient.Models.CreateAccountingBankfeedaccountFieldsParameterItem[] Fields { get; set; }
#endif
            /// <summary>&quot;Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("raw")]
            public string? Raw { get; set; }
#nullable restore
#else
            [QueryParameter("raw")]
            public string Raw { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
