// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Commerce.Item.Reservation.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "location_id")]
        #pragma warning disable CS1591
        Location_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_at")]
        #pragma warning disable CS1591
        Start_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_at")]
        #pragma warning disable CS1591
        End_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "size")]
        #pragma warning disable CS1591
        Size,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "guest_name")]
        #pragma warning disable CS1591
        Guest_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "guest_phone")]
        #pragma warning disable CS1591
        Guest_phone,
        #pragma warning restore CS1591
        [EnumMember(Value = "guest_email")]
        #pragma warning disable CS1591
        Guest_email,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes")]
        #pragma warning disable CS1591
        Notes,
        #pragma warning restore CS1591
        [EnumMember(Value = "item_id")]
        #pragma warning disable CS1591
        Item_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "item_name")]
        #pragma warning disable CS1591
        Item_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "staff_user_id")]
        #pragma warning disable CS1591
        Staff_user_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "staff_name")]
        #pragma warning disable CS1591
        Staff_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        Updated_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
