// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Unified.OpenApiClient.Payment.Item.Payout
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        Updated_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "total_amount")]
        #pragma warning disable CS1591
        Total_amount,
        #pragma warning restore CS1591
        [EnumMember(Value = "currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes")]
        #pragma warning disable CS1591
        Notes,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
    }
}
